/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.keyan.hibernate.dao.DataDAO;

/**
 * MyEclipse Struts Creation date: 11-04-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/data" name="dataForm" parameter="method"
 *                scope="request" validate="true"
 * @struts.action-forward name="fail" path="/fail.jsp" redirect="true"
 */
public class DataAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String method = request.getParameter("method");
		ServletContext con = this.servlet.getServletContext();

		DataDAO dataDAO = new DataDAO();

		if (method.equals("beifen")) {
			dataDAO.backup();
			con.setAttribute("result", "备份数据库成功，备份的后文件夹是kygl");
			return mapping.findForward("data");
		} else if (method.equals("huanyuan")) {
			String url = request.getParameter("huanyuanurl");

			dataDAO.load(url);
			con.setAttribute("result", "还原数据库成功，还原的后文件夹是kygl");
			return mapping.findForward("huanyuan");
		}

		return null;
	}
}