/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.keyan.hibernate.dao.GgDAO;
import com.keyan.hibernate.form.Gg;
import com.keyan.struts.form.GgForm;

/**
 * MyEclipse Struts Creation date: 10-05-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/gg" name="ggForm" parameter="method" scope="request"
 *                validate="true"
 * @struts.action-forward name="fail1" path="/fail.jsp" redirect="true"
 */
public class GgAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if (request.getSession().getAttribute("keyanuser") == null) {
			return mapping.findForward("logout");
		}
		GgForm ggForm = (GgForm) form;// TODO Auto-generated method stub
		String method = (String) request.getParameter("method");

		ActionForward forward = new ActionForward();
		ServletContext context = this.servlet.getServletContext();
		List list = new ArrayList();
		Gg tbManager = new Gg();
		GgDAO managerDAO = new GgDAO();

		if (method.equals("query")) {

			try {

				list = managerDAO.query();

				context.setAttribute("list", list);				
				return mapping.findForward("GgList");
			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("insert")) {
			try {

				String url = null;

				tbManager.setContext(ggForm.getContext());

				managerDAO.insert(tbManager);

				url = "gg.do?method=query";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);

				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele")) {
			try {
				String url = null;
				String id = request.getParameter("id");

				managerDAO.delete(new Integer(id));

				url = "gg.do?method=query";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);

				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		return null;

	}
}
