/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.keyan.hibernate.dao.ProjectcgDao;
import com.keyan.hibernate.dao.ThesisDao;
import com.keyan.hibernate.dao.UnitDAO;
import com.keyan.hibernate.dao.UserDAO;
import com.keyan.hibernate.dao.WorkDao;
import com.keyan.hibernate.dao.ZhuanliDao;
import com.keyan.hibernate.form.Keyanuser;
import com.keyan.hibernate.form.Unit;
import com.keyan.struts.form.BgLoginForm;

/**
 * MyEclipse Struts Creation date: 07-28-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/login" name="loginForm" input="/login.jsp"
 *                parameter="method" scope="request" validate="true"
 * @struts.action-forward name="failure" path="/failure.jsp"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class LoginAction extends Action {
	/*
	 * 继承Action,这样就可以直接使用SUCCESS Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BgLoginForm loginForm = (BgLoginForm) form;// TODO Auto-generated method
													// stub
		// 获得输入框中的用户及密码

		String username = loginForm.getUsername();
		String password1 = loginForm.getPassword();
		String password = UserAction.MD5Password(password1);

		String userType = loginForm.getClasify();
		HttpSession session = request.getSession(false);

		if (session != null) {

			session.invalidate();

		}
		Date date = new Date();
		int nian = date.getYear() + 1900;		
		session = request.getSession(true);
		ThesisDao thesisDao = new ThesisDao();
		ProjectcgDao projectcgDao = new ProjectcgDao();
		WorkDao workDao = new WorkDao();
		ZhuanliDao zhuanliDao = new ZhuanliDao();
		List list = new ArrayList();
		Integer thesisnum = thesisDao.findByUserNian(nian);
		Integer worknum = workDao.findByUserNian(nian);
		Integer projectcgnum = ProjectcgDao.findByUserNian(nian);
		Integer zhuanlinum = zhuanliDao.findByUserNian(nian);
		UserDAO userDAO = new UserDAO();
		Keyanuser keyanuser = new Keyanuser();
		list.add(thesisnum);
		list.add(worknum);
		list.add(projectcgnum);
		list.add(projectcgnum);
		keyanuser = userDAO.qurryuser(username, password, userType);
		UnitDAO unitDAO = new UnitDAO();
		List unitlist = unitDAO.findAll();
		List list1 = new ArrayList();
		for (int i = 0; i < unitlist.size(); i++) {

			Unit unit = (Unit) unitlist.get(i);
			Integer number1 = thesisDao.queryByUserdept(unit.getUnitname(),
					nian);
			Integer number2 = workDao.queryByUserdept(unit.getUnitname(), nian);
			Integer number3 = projectcgDao.queryByUserdept(unit.getUnitname(),
					nian);
			Integer number4 = zhuanliDao.queryByUserdept(unit.getUnitname(),
					nian);
			list1.add(number1);
			list1.add(number2);
			list1.add(number3);
			list1.add(number4);			
		}

		// 如果用户查询结果不为空
		if (keyanuser != null) {
			// 把用户和密码放在session内
			session.setAttribute("list1", list);
			session.setAttribute("keyanuser", keyanuser);
			session.setAttribute("username", keyanuser.getName());
			session.setAttribute("unitlist", list1);
			// 发向strust——config.xml-maim
			return mapping.findForward("main");
		} else {

			return mapping.findForward("failure");
		}
	}
}