/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.keyan.hibernate.dao.PppeopleDao;
import com.keyan.hibernate.dao.Project1Dao;
import com.keyan.hibernate.form.Keyanuser;
import com.keyan.hibernate.form.Pppeople;
import com.keyan.hibernate.form.Project1;
import com.keyan.struts.form.Project1Form;

/**
 * MyEclipse Struts Creation date: 02-26-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action input="/projectxx.jsp" parameter="method" validate="true"
 * @struts.action-forward name="fail1" path="/fail1.jsp"
 * @struts.action-forward name="success1" path="/success.jsp"
 */
public class Project1Action extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("keyanuser") == null) {
			return mapping.findForward("logout");
		}
		Project1Form project1form = (Project1Form) form;
		String method = (String) request.getParameter("method");
		ActionErrors errors = new ActionErrors();
		ActionForward forward = new ActionForward();
		ServletContext context = this.servlet.getServletContext();
		List list = new ArrayList();

		Project1 project1 = new Project1();
		HttpSession sesssion = request.getSession();
		Keyanuser keyanuser = new Keyanuser();
		// 获得用户名，权限和所属院系
		keyanuser = (Keyanuser) request.getSession().getAttribute("keyanuser");
		String userclasify = keyanuser.getUserclasify();
		String userdept = keyanuser.getUserdept();
		String username = keyanuser.getName();
		String usernum = keyanuser.getUsername();

		// ------项目申报----------
		if (method.equals("query")) {
			List list2 = new ArrayList();
			List list1 = new ArrayList();
			List list5 = new ArrayList();
			List list6 = new ArrayList();
			Project1Dao project1Dao = new Project1Dao();
			PppeopleDao pppeopleDao = new PppeopleDao();
			if (userclasify.equals("0")) {
				list5 = pppeopleDao.queryPpusernum(usernum);

				for (int i = 0; i < list5.size(); i++) {
					Pppeople pppeople = (Pppeople) list5.get(i);
					list = project1Dao.findall2(userclasify, userdept,
							pppeople.getPid());

					if (!(0 == list.size())) {
						list6.add(list.get(0));
					}
				}

			} else {
				list6 = project1Dao.findall2(userclasify, userdept, username);
			}

			for (int i = 0; i < list6.size(); i++) {
				String other = "";
				Project1 project12 = (Project1) list6.get(i);
				/* list长度为0 */

				list1 = pppeopleDao.queryPid(project12.getPid());

				for (int j = 0; j < list1.size(); j++) {
					Pppeople pppeople = (Pppeople) list1.get(j);
					if (j == 0) {
						other = pppeople.getPpname();
					} else {
						other = other + "," + pppeople.getPpname();
					}
				}
				list2.add(other);
			}

			context.setAttribute("list2", list2);
			context.setAttribute("list", list6);
			if (userclasify.equals("2")) {
				return mapping.findForward("xmguanli");

			} else if (userclasify.equals("1") || userclasify.equals("0")) {
				return mapping.findForward("xmguanli1");

			}
		}

		// ----------------立项查看------------

		else if (method.equals("query111")) {
			Project1Dao project1Dao = new Project1Dao();
			List list2 = new ArrayList();
			List list1 = new ArrayList();
			List list5 = new ArrayList();
			List list6 = new ArrayList();

			PppeopleDao pppeopleDao = new PppeopleDao();
			if (userclasify.equals("0")) {
				list5 = pppeopleDao.queryPpusernum(usernum);

				for (int i = 0; i < list5.size(); i++) {
					Pppeople pppeople = (Pppeople) list5.get(i);
					list = project1Dao.findall111(userclasify, userdept,
							pppeople.getPid());
					if (!(0 == list.size())) {
						list6.add(list.get(0));
					}

				}
			} else {
				list6 = project1Dao.findall111(userclasify, userdept, username);
			}

			for (int i = 0; i < list6.size(); i++) {
				String other = "";
				Project1 project12 = (Project1) list6.get(i);
				/* list长度为0 */

				list1 = pppeopleDao.queryPid(project12.getPid());

				for (int j = 0; j < list1.size(); j++) {
					Pppeople pppeople = (Pppeople) list1.get(j);
					if (j == 0) {
						other = pppeople.getPpname();
					} else {
						other = other + "," + pppeople.getPpname();
					}
				}
				list2.add(other);
			}

			context.setAttribute("list2", list2);
			context.setAttribute("list", list6);
			return mapping.findForward("lixiang");

		}

		// 中检查看
		else if (method.equals("query112")) {
			Project1Dao project1Dao = new Project1Dao();

			List list2 = new ArrayList();
			List list1 = new ArrayList();
			List list5 = new ArrayList();
			List list6 = new ArrayList();

			PppeopleDao pppeopleDao = new PppeopleDao();
			if (userclasify.equals("0")) {
				list5 = pppeopleDao.queryPpusernum(usernum);

				for (int i = 0; i < list5.size(); i++) {
					Pppeople pppeople = (Pppeople) list5.get(i);
					list = project1Dao.findall112(userclasify, userdept,
							pppeople.getPid());
					if (!(0 == list.size())) {
						list6.add(list.get(0));
					}

				}
			} else {
				list6 = project1Dao.findall112(userclasify, userdept, username);
			}

			for (int i = 0; i < list6.size(); i++) {
				String other = "";
				Project1 project12 = (Project1) list6.get(i);
				/* list长度为0 */

				list1 = pppeopleDao.queryPid(project12.getPid());

				for (int j = 0; j < list1.size(); j++) {
					Pppeople pppeople = (Pppeople) list1.get(j);
					if (j == 0) {
						other = pppeople.getPpname();
					} else {
						other = other + "," + pppeople.getPpname();
					}
				}
				list2.add(other);
			}
			context.setAttribute("list2", list2);

			context.setAttribute("list", list6);
			return mapping.findForward("zhongjian");

		}

		// 结项查看
		else if (method.equals("query113")) {
			Project1Dao project1Dao = new Project1Dao();

			context.setAttribute("list", list);

			List list2 = new ArrayList();
			List list1 = new ArrayList();
			List list5 = new ArrayList();
			List list6 = new ArrayList();

			PppeopleDao pppeopleDao = new PppeopleDao();
			if (userclasify.equals("0")) {
				list5 = pppeopleDao.queryPpusernum(usernum);

				for (int i = 0; i < list5.size(); i++) {
					Pppeople pppeople = (Pppeople) list5.get(i);
					list = project1Dao.findall113(userclasify, userdept,
							pppeople.getPid());
					if (!(0 == list.size())) {
						list6.add(list.get(0));
					}

				}
			} else {
				list6 = project1Dao.findall113(userclasify, userdept, username);
			}

			for (int i = 0; i < list6.size(); i++) {
				String other = "";
				Project1 project12 = (Project1) list6.get(i);
				/* list长度为0 */

				list1 = pppeopleDao.queryPid(project12.getPid());

				for (int j = 0; j < list1.size(); j++) {
					Pppeople pppeople = (Pppeople) list1.get(j);
					if (j == 0) {
						other = pppeople.getPpname();
					} else {
						other = other + "," + pppeople.getPpname();
					}
				}
				list2.add(other);
			}
			context.setAttribute("list2", list2);

			context.setAttribute("list", list6);
			return mapping.findForward("jiexiang");

		}

		// --------------延期查看----------
		else if (method.equals("query114")) {
			Project1Dao project1Dao = new Project1Dao();

			List list2 = new ArrayList();
			List list1 = new ArrayList();
			List list5 = new ArrayList();
			List list6 = new ArrayList();

			PppeopleDao pppeopleDao = new PppeopleDao();
			if (userclasify.equals("0")) {
				list5 = pppeopleDao.queryPpusernum(usernum);

				for (int i = 0; i < list5.size(); i++) {
					Pppeople pppeople = (Pppeople) list5.get(i);
					list = project1Dao.findall114(userclasify, userdept,
							pppeople.getPid());
					if (!(0 == list.size())) {
						list6.add(list.get(0));
					}

				}
			} else {
				list6 = project1Dao.findall114(userclasify, userdept, username);
			}

			for (int i = 0; i < list6.size(); i++) {
				String other = "";
				Project1 project12 = (Project1) list6.get(i);
				/* list长度为0 */

				list1 = pppeopleDao.queryPid(project12.getPid());

				for (int j = 0; j < list1.size(); j++) {
					Pppeople pppeople = (Pppeople) list1.get(j);
					if (j == 0) {
						other = pppeople.getPpname();
					} else {
						other = other + "," + pppeople.getPpname();
					}
				}
				list2.add(other);
			}
			context.setAttribute("list2", list2);

			context.setAttribute("list", list6);

			return mapping.findForward("yanqi");
		}

		// 项目终止查看
		else if (method.equals("query115")) {
			Project1Dao project1Dao = new Project1Dao();

			List list2 = new ArrayList();
			List list1 = new ArrayList();
			List list5 = new ArrayList();
			List list6 = new ArrayList();

			PppeopleDao pppeopleDao = new PppeopleDao();
			if (userclasify.equals("0")) {
				list5 = pppeopleDao.queryPpusernum(usernum);

				for (int i = 0; i < list5.size(); i++) {
					Pppeople pppeople = (Pppeople) list5.get(i);
					list = project1Dao.findall115(userclasify, userdept,
							pppeople.getPid());
					if (!(0 == list.size())) {
						list6.add(list.get(0));
					}

				}
			} else {
				list6 = project1Dao.findall115(userclasify, userdept, username);
			}

			for (int i = 0; i < list6.size(); i++) {
				String other = "";
				Project1 project12 = (Project1) list6.get(i);
				/* list长度为0 */

				list1 = pppeopleDao.queryPid(project12.getPid());

				for (int j = 0; j < list1.size(); j++) {
					Pppeople pppeople = (Pppeople) list1.get(j);
					if (j == 0) {
						other = pppeople.getPpname();
					} else {
						other = other + "," + pppeople.getPpname();
					}
				}
				list2.add(other);
			}
			context.setAttribute("list2", list2);

			context.setAttribute("list", list6);
			return mapping.findForward("zhongzhi");
		} else if (method.equals("insert")) {
			String filePath = null;
			String path = null;

			if (project1form.getPadjuct().getFileName() == null
					|| project1form.getPadjuct().getFileName().equals("")) {
				try {
					Date d = new Date();
					Project1Dao project1Dao = new Project1Dao();
					project1.setPadjuct("");
					project1.setPclassify(project1form.getPclassify());
					project1.setPcome(project1form.getPcome());
					project1.setPcontrol(project1form.getPcontrol());
					project1.setPdept(project1form.getPdept());
					project1.setPfinish(project1form.getPfinish());
					project1.setPform(project1form.getPform());
					project1.setPname(project1form.getPname());
					project1.setPnum(project1form.getPnum());
					project1.setPremark(project1form.getPremark());
					project1.setPstar(project1form.getPstar());
					project1.setUsernum(usernum);
					project1.setPstate1("未审核");
					project1.setPstate2("未审核");
					project1.setPstate3("未审核");
					project1.setOther(d.toString());
					project1Dao.insert(project1);
					Project1 project11 = project1Dao.queryOther(d.toString());
					String pid = project11.getPid().toString();
					context.setAttribute("pid1", pid);

					return mapping.findForward("addpeople");
				} catch (Exception e) {
					return mapping.findForward("fail1");
				}
			} else {

				FormFile file = project1form.getPadjuct();// 获得文件
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();
				long FILE_SISE = 0x265480L;// 定义最大文件大小
				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdirs();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();

						Project1Dao project1Dao = new Project1Dao();
						Date d = new Date();
						project1.setPadjuct(filePath + "/" + fileName);
						project1.setPclassify(project1form.getPclassify());
						project1.setPcome(project1form.getPcome());
						project1.setPcontrol(project1form.getPcontrol());
						project1.setPdept(project1form.getPdept());
						project1.setPfinish(project1form.getPfinish());
						project1.setPform(project1form.getPform());
						project1.setPname(project1form.getPname());
						project1.setPnum(project1form.getPnum());
						project1.setPremark(project1form.getPremark());
						project1.setPstar(project1form.getPstar());
						project1.setUsernum(usernum);
						project1.setPstate1("未审核");
						project1.setPstate2("未审核");
						project1.setPstate3("未审核");
						project1.setOther(d.toString());
						project1Dao.insert(project1);

						Project1 project11 = project1Dao.queryOther(d
								.toString());

						String pid = project11.getPid().toString();
						context.setAttribute("pid1", pid);
						return mapping.findForward("addpeople");

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();;
					}

			}
		}
		// 文件上传
		else if (method.equals("upload3")) {
			String filePath = null;
			String path = null;

			FormFile file = project1form.getPadjuct();// 获得文件
			if (file != null && !file.getFileName().equals("")) {
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();
				long FILE_SISE = 0x265480L;// 定义最大文件大小
				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdirs();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();

						Project1Dao project1Dao = new Project1Dao();

						project1 = project1Dao.queryId(project1form.getPid());

						project1.setPadjuct(filePath + "/" + fileName);

						project1Dao.update1(project1);

						// 跳回原来的页面
						String url = "project1.do?method=query113";
						forward.setPath(url);
						forward.setRedirect(true);

						return forward;

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();
					}

			}

		}
		// 文件上传
		else if (method.equals("upload2")) {
			String filePath = null;
			String path = null;

			FormFile file = project1form.getPadjuct();// 获得文件
			if (file != null && !file.getFileName().equals("")) {
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();
				long FILE_SISE = 0x265480L;// 定义最大文件大小
				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdirs();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();

						Project1Dao project1Dao = new Project1Dao();

						project1 = project1Dao.queryId(project1form.getPid());

						project1.setPadjuct(filePath + "/" + fileName);

						project1Dao.update1(project1);

						// 跳回原来的页面
						String url = "project1.do?method=query111";
						forward.setPath(url);
						forward.setRedirect(true);

						return forward;

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();
					}

			}

		}

		// 文件上传
		else if (method.equals("upload1")) {
			String filePath = null;
			String path = null;

			FormFile file = project1form.getPadjuct();// 获得文件
			if (file != null && !file.getFileName().equals("")) {
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();
				long FILE_SISE = 0x265480L;// 定义最大文件大小
				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdirs();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();

						Project1Dao project1Dao = new Project1Dao();

						project1 = project1Dao.queryId(project1form.getPid());

						project1.setPadjuct(filePath + "/" + fileName);

						project1Dao.update1(project1);

						// 跳回原来的页面
						String url = "project1.do?method=query112";
						forward.setPath(url);
						forward.setRedirect(true);

						return forward;

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();
					}

			}

		}
		// 文件上传
		else if (method.equals("upload")) {
			String filePath = null;
			String path = null;

			FormFile file = project1form.getPadjuct();// 获得文件
			if (file != null && !file.getFileName().equals("")) {
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();
				long FILE_SISE = 0x265480L;// 定义最大文件大小
				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdirs();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();
						Project1Dao project1Dao = new Project1Dao();

						project1 = project1Dao.queryId(project1form.getPid());

						project1.setPadjuct(filePath + "/" + fileName);

						project1Dao.update1(project1);

						// 跳回原来的页面
						String url = "project1.do?method=query114";
						forward.setPath(url);
						forward.setRedirect(true);

						return forward;

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();
					}

			}

		} else if (method.equals("insert11"))// 校审批通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));
			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate2("校审通过");
				project1Dao.update1(project1);
				Project1Dao project2Dao = new Project1Dao();
				list = project2Dao.findall2(userclasify, userdept, username);
				context.setAttribute("list", list);
				return mapping.findForward("xmguanli");
			} else if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate1("系审通过");
				project1Dao.update1(project1);
				return new ActionForward("/project1.do?method=query");
			}
			forward.setRedirect(true);
			return forward;
		} else if (method.equals("insert12"))// 校审批不通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));
			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate2("校审不通过");
				project1Dao.update1(project1);
				Project1Dao project2Dao = new Project1Dao();
				list = project2Dao.findall2(userclasify, userdept, username);
				context.setAttribute("list", list);
				return mapping.findForward("xmguanli");
			} else if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate1("系审不通过");
				project1Dao.update1(project1);
				return new ActionForward("/project1.do?method=query");
			}
			forward.setRedirect(true);
			return forward;
		}

		else if (method.equals("insert13"))// 立项
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));
			project1.setPstatus("立项");
			project1Dao.update1(project1);
			Project1Dao project2Dao = new Project1Dao();
			return new ActionForward("/project1.do?method=query");
		}

		else if (method.equals("delete")) {
			try {
				Project1Dao project1Dao = new Project1Dao();
				String id = request.getParameter("id");
				project1Dao.delete(new Integer(id));
				PppeopleDao pppeopleDao = new PppeopleDao();
				pppeopleDao.delete(id);
				System.out.println("-----------------");
				List list2 = new ArrayList();
				List list1 = new ArrayList();
				List list5 = new ArrayList();
				List list6 = new ArrayList();

				if (userclasify.equals("0")) {
					list5 = pppeopleDao.queryPpusernum(usernum);

					for (int i = 0; i < list5.size(); i++) {
						Pppeople pppeople = (Pppeople) list5.get(i);
						list = project1Dao.findall2(userclasify, userdept,
								pppeople.getPid());

						if (!(0 == list.size())) {
							list6.add(list.get(0));
						}
					}

				} else {
					list6 = project1Dao.findall2(userclasify, userdept,
							username);
				}

				for (int i = 0; i < list6.size(); i++) {
					String other = "";
					Project1 project12 = (Project1) list6.get(i);
					/* list长度为0 */

					list1 = pppeopleDao.queryPid(project12.getPid());

					for (int j = 0; j < list1.size(); j++) {
						Pppeople pppeople = (Pppeople) list1.get(j);
						if (j == 0) {
							other = pppeople.getPpname();
						} else {
							other = other + "," + pppeople.getPpname();
						}
					}
					list2.add(other);
				}

				context.setAttribute("list2", list2);
				context.setAttribute("list", list6);
				if (userclasify.equals("2")) {
					return mapping.findForward("xmguanli");

				} else if (userclasify.equals("1") || userclasify.equals("0")) {
					return mapping.findForward("xmguanli1");

				}
				if (userclasify.equals("2")) {
					return new ActionForward("/project1.do?method=query");
				} else if (userclasify.equals("1") || userclasify.equals("0")) {
					return new ActionForward("/project1.do?method=query");
				}
				return forward;

			} catch (Exception e) {
				return new ActionForward("/project1.do?method=query");
			}
		}

		else if (method.equals("qury441"))// 查询
		{
			List list3 = new ArrayList();

			try {
				Project1Dao project1Dao = new Project1Dao();
				String pnum = request.getParameter("pnum");
				String pname = request.getParameter("pname");
				String pcome = request.getParameter("pcome");
				String pclassify = request.getParameter("pclassify");
				String pcontrol = request.getParameter("pcontrol");
				String pdept = request.getParameter("pdept");
				String pform = request.getParameter("pform");
				String pstate1 = request.getParameter("pstate1");
				String pstate2 = request.getParameter("pstate2");
				String pstar1 = request.getParameter("pstar1");
				String pstar2 = request.getParameter("pstar2");
				list3 = project1Dao.queryByName(pnum, pname, pcome, pclassify,
						pcontrol, pdept, pform, pstate1, pstate2, pstar1,
						pstar2, userdept);

				context.setAttribute("list", list3);

				return mapping.findForward("xmguanli");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("update"))// 点击编辑时把当前的数据项放到project1中
		{
			try {
				Project1Dao project1Dao = new Project1Dao();
				String id = request.getParameter("id");
				project1 = project1Dao.queryId(new Integer(id));
				context.setAttribute("project1", project1);
				return mapping.findForward("updateproject1");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("update1"))// 编辑后对数据进行更新
		{
			String filePath = null;
			String path = null;
			Date d = new Date();
			try {
				Project1Dao project1Dao = new Project1Dao();
				project1.setPid(project1form.getPid());
				project1.setPclassify(project1form.getPclassify());
				project1.setPcome(project1form.getPcome());
				project1.setPcontrol(project1form.getPcontrol());
				project1.setPdept(project1form.getPdept());
				project1.setPfinish(project1form.getPfinish());
				project1.setPform(project1form.getPform());
				project1.setPname(project1form.getPname());
				project1.setPnum(project1form.getPnum());
				project1.setPremark(project1form.getPremark());
				project1.setPstar(project1form.getPstar());
				project1.setPstate1(project1form.getPstate1());
				project1.setPstate2(project1form.getPstate2());
				project1.setPstate3(project1form.getPstate3());
				project1.setOther(d.toString());
				project1.setUsernum(usernum);
				project1Dao.update1(project1);
				Project1Dao project2Dao = new Project1Dao();

				list = project2Dao.findall2(userclasify, userdept, usernum);
				context.setAttribute("list", list);
				if (userclasify.equals("2")) {

					return new ActionForward("/project1.do?method=query");
				} else if (userclasify.equals("1") || userclasify.equals("0")) {
					return new ActionForward("/project1.do?method=query");
				}
			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		// 申请中检；立项审批通过
		else if (method.equals("insert1111")) {
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("0")) {
				project1.setPstatus("中检");
			} else if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("立项1");
			} else if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("立项2");
			}
			project1Dao.update1(project1);
			return new ActionForward("/project1.do?method=query111");

		}

		else if (method.equals("insert1112"))// 项目终止；立项审批不同
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));
			if (keyanuser.getUserclasify().equals("0")) {
				project1.setPstatus("终止");
			} else if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("立项11");
			} else if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("立项22");
			}
			project1Dao.update1(project1);

			return new ActionForward("/project1.do?method=query111");
		} else if (method.equals("insert1121"))// 结项申请；中检审批批通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("中检2");
			}
			if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("中检1");
			}
			if (keyanuser.getUserclasify().equals("0")) {
				project1.setPstatus("结项");
			}
			project1Dao.update1(project1);
			return new ActionForward("/project1.do?method=query112");
		} else if (method.equals("insert1122"))// 延期申请；中检审批不通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("2")) {
			//	project1.setPstatus("中检");
				project1.setPstate3("中检22");
			}
			if (keyanuser.getUserclasify().equals("1")) {
			//	project1.setPstatus("中检");
				project1.setPstate3("中检11");
			}
			if (keyanuser.getUserclasify().equals("0")) {
				project1.setPstatus("延期");
			}
			project1Dao.update1(project1);
			return new ActionForward("/project1.do?method=query112");
		} else if (method.equals("insert1131"))// 延期申请；结项通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));
			if (keyanuser.getUserclasify().equals("0")) {
				project1.setPstatus("延期");
			}
			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("结项2");
			}
			if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("结项1");
			}
			project1Dao.update1(project1);
			Project1Dao project2Dao = new Project1Dao();
			return new ActionForward("/project1.do?method=query113");
		} else if (method.equals("insert1132"))// 结项审批不通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("2")) {

				project1.setPstate3("结项22");
			}
			if (keyanuser.getUserclasify().equals("1")) {

				project1.setPstate3("结项11");
			}
			project1Dao.update1(project1);
			return new ActionForward("/project1.do?method=query113");
		} else if (method.equals("insert1141"))// 结项申请；延期审批通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("延期2");
			}
			if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("延期1");
			}
			if (keyanuser.getUserclasify().equals("0")) {
				project1.setPstatus("结项");
			}
			project1Dao.update1(project1);

			return new ActionForward("/project1.do?method=query114");
		} else if (method.equals("insert1142"))// 延期审批不通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("校审通过");
				project1.setPstatus("终止");
			}
			if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("系审通过");
				project1.setPstatus("终止");
			}

			return new ActionForward("/project1.do?method=query114");
		} else if (method.equals("insert1151"))// 终止审批通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("校审通过");
			}
			if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("系审通过");
			}
			project1Dao.update1(project1);
			Project1Dao project2Dao = new Project1Dao();
			return new ActionForward("/project1.do?method=query115");
		}

		else if (method.equals("insert1152"))// 终止审批不通过
		{
			String id = request.getParameter("id");
			Project1Dao project1Dao = new Project1Dao();
			project1 = project1Dao.queryId(new Integer(id));

			if (keyanuser.getUserclasify().equals("2")) {
				project1.setPstate3("延期2");
				project1.setPstatus("延期");
			}
			if (keyanuser.getUserclasify().equals("1")) {
				project1.setPstate3("延期2");
				project1.setPstatus("延期");
			}
			project1Dao.update1(project1);


		}
		return new ActionForward("/project1.do?method=query115");

	}

}