/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.keyan.hibernate.dao.ThesisDao;
import com.keyan.hibernate.form.Keyanuser;
import com.keyan.hibernate.form.Thesis;
import com.keyan.struts.form.ThesisForm;

/**
 * MyEclipse Struts Creation date: 10-05-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/thesis" name="thesisForm" input="/thesis.jsp"
 *                parameter="method" scope="request" validate="true"
 */
public class ThesisAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		if (request.getSession().getAttribute("keyanuser") == null) {
			return mapping.findForward("logout");
		}

		ThesisForm thesisForm = (ThesisForm) form;// TODO Auto-generated method
													// stub
		String method = (String) request.getParameter("method");
		ActionErrors errors = new ActionErrors();
		ActionForward forward = new ActionForward();
		ServletContext context = this.servlet.getServletContext();
		List list = new ArrayList();
		Thesis thesis = new Thesis();

		ThesisDao thesisDao = new ThesisDao();
		HttpSession sesssion = request.getSession();

		if (method.equals("query")) {

			String wd = request.getParameter("wd");
			try {
				Keyanuser keyanuser = new Keyanuser();
				keyanuser = (Keyanuser) request.getSession().getAttribute(
						"keyanuser");

				if (wd != null) {
					if (keyanuser.getUserclasify().equals("0")) {
						// 科研人员
						list = thesisDao
								.queryBy(wd, keyanuser.getUserclasify());
					} else if (keyanuser.getUserclasify().equals("1")) {
						// 院科研秘书
						list = thesisDao
								.queryBy(wd, keyanuser.getUserclasify());
					} else {
						// 校科研秘书
						list = thesisDao
								.queryBy(wd, keyanuser.getUserclasify());
					}

				} else {

					if (keyanuser.getUserclasify().equals("0")) {
						// 科研人员
						list = thesisDao.query(keyanuser.getUserclasify());
					} else if (keyanuser.getUserclasify().equals("1")) {
						// 院科研秘书
						list = thesisDao.query(keyanuser.getUserclasify());
					} else {
						// 校科研秘书
						list = thesisDao.query(keyanuser.getUserclasify());
					}
				}

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query33")) {

			String wd = request.getParameter("wd");

			try {

				String username = (String) request.getSession().getAttribute(
						"username");

				list = thesisDao.queryByname(username, wd);

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query331")) {

			String wd = request.getParameter("wd");

			try {
				Keyanuser keyanuser = (Keyanuser) request.getSession()
						.getAttribute("keyanuser");
				String userdept = keyanuser.getUserdept();

				list = thesisDao.queryByunit(userdept, wd);

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("query31")) {

			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			try {

				list = thesisDao.queryByName(keyanuser.getUsername());

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query41")) {

			try {
				String username = request.getParameter("byName");
				String unit = request.getParameter("byUnit");
				String post = request.getParameter("byPost");
				String title = request.getParameter("byTitle");
				list = thesisDao.queryByName(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query441")) {

			try {
				String username = request.getParameter("byName");
				String unit = request.getParameter("byUnit");
				String post = request.getParameter("byPost");

				String title = request.getParameter("byTitle");
				list = thesisDao.queryByName1(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query442")) {

			try {
				Keyanuser keyanuser = (Keyanuser) request.getSession()
						.getAttribute("keyanuser");
				String unit = keyanuser.getUserdept();
				String username = request.getParameter("byName");

				String post = request.getParameter("byPost");

				String title = request.getParameter("byTitle");
				list = thesisDao.queryByName2(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query443")) {

			try {
				String username = (String) request.getSession().getAttribute(
						"username");
				String unit = request.getParameter("byUnit");
				String post = request.getParameter("byPost");

				String title = request.getParameter("byTitle");
				list = thesisDao.queryByName3(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		}
		// 更新
		else if (method.equals("update1")) {
			String id = request.getParameter("id");
			thesis = thesisDao.queryId(new Integer(id));
			Keyanuser keyanuser = new Keyanuser();
			keyanuser = (Keyanuser) request.getSession().getAttribute(
					"keyanuser");

			if (keyanuser.getUserclasify().equals("0")) {
				// work.setWScore(1);
			} else if (keyanuser.getUserclasify().equals("1")) {
				if (thesis.getTScore().equals("未审核"))
					thesis.setTScore("院审通过");
			} else {
				thesis.setTScore("校审通过");
			}

			thesisDao.update1(thesis);

			String url = "thesis.do?method=query32";
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;

		} else if (method.equals("update2")) {
			String id = request.getParameter("id");
			thesis = thesisDao.queryId(new Integer(id));
			Keyanuser keyanuser = new Keyanuser();
			keyanuser = (Keyanuser) request.getSession().getAttribute(
					"keyanuser");

			if (keyanuser.getUserclasify().equals("0")) {
				// work.setWScore(1);
			} else if (keyanuser.getUserclasify().equals("1")) {
				if (thesis.getTScore().equals("未审核"))
					thesis.setTScore("院审通过");
			} else {
				thesis.setTScore("校审通过");
			}

			thesisDao.update1(thesis);

			String url = "thesis.do?method=query";
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;

		}

		else if (method.equals("query32")) {

			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			try {

				list = thesisDao.queryByUserdept(keyanuser.getUserdept());

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}

		} else if (method.equals("detele1")) {
			try {

				String id = request.getParameter("id");

				thesisDao.delete(new Integer(id));

				String url = "thesis.do?method=query31";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele2")) {
			try {

				String id = request.getParameter("id");

				thesisDao.delete(new Integer(id));

				String url = "thesis.do?method=query32";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele3")) {
			try {

				String id = request.getParameter("id");

				thesisDao.delete(new Integer(id));

				String url = "thesis.do?method=query";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query1")) {
			try {

				String id = request.getParameter("id");

				thesis = thesisDao.queryId(new Integer(id));

				context.setAttribute("thesis", thesis);

				return mapping.findForward("query2");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("queryinfo")) {
			try {

				String id = request.getParameter("id");

				thesis = thesisDao.queryId(new Integer(id));

				context.setAttribute("thesis", thesis);

				return mapping.findForward("queryinfo");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("insert")) {
			Keyanuser keyanuser = (Keyanuser) request.getSession()
					.getAttribute("keyanuser");
			String filePath = null;
			String path = null;
			String url = null;
			if (thesisForm.getFile().getFileName().equals("")) {
				try {

					Date d = new Date();
					thesis.setTName(thesisForm.getT_name());
					thesis.setTPost(thesisForm.getT_post());
					thesis.setTUnit(thesisForm.getT_unit());
					thesis.setTTitle(thesisForm.getT_title());
					thesis.setTPeriodical(thesisForm.getT_periodical());
					thesis.setTCnid(thesisForm.getT_CNId());
					thesis.setTIssnid(thesisForm.getT_ISSNId());
					thesis.setTTime(d);

					String tusernum = keyanuser.getUsername();
					thesis.setTnum(tusernum);

					thesis.setTScore("未审核");
					thesis.setTRemarks(thesisForm.getT_remarks());

					int num;
					if (!"".equals(thesisForm.getSecond().replace(" ", ""))
							&& !"".equals(thesisForm.getSecondnum().replace(
									" ", ""))) {
						num = 2;
						thesis.setSecond(thesisForm.getSecond());
						tusernum = tusernum + "," + thesisForm.getSecondnum();

						if (!"".equals(thesisForm.getThird().replace(" ", ""))) {
							num = 3;
							tusernum = tusernum + ","
									+ thesisForm.getThirdnum();
							thesis.setThird(thesisForm.getThird());
							if (!"".equals(thesisForm.getT_others().replace(
									" ", ""))) {
								tusernum = tusernum + ","
										+ thesisForm.getT_othersnum();
								num = 3 + thesisForm.getT_others().split("、").length;
								thesis.setTOthers(thesisForm.getT_others());
							} else {
								thesis.setTOthers("无");
							}
						} else {
							thesis.setThird("无");
							thesis.setTOthers("无");
						}
						thesis.setTMembers(num);

					} else {
						thesis.setSecond("无");
						thesis.setTMembers(1);
						thesis.setThird("无");
						thesis.setTOthers("无");
					}

					if (thesisForm.getT_remarks().equals("SCI、SSCI全文收录")) {
						thesis.setAchnum("1");

					} else if (thesisForm.getT_remarks().equals("EI、ISSHP检索收录")) {
						thesis.setAchnum("2");

					} else if (thesisForm.getT_remarks().equals("国家一级刊物")) {
						thesis.setAchnum("3");

					} else if (thesisForm.getT_remarks().equals("全国中文核心学术期刊")) {
						thesis.setAchnum("4");

					} else if (thesisForm.getT_remarks().equals("普通CN期刊")) {
						thesis.setAchnum("5");

					} else if (thesisForm.getT_remarks().equals("国家级报纸理论")) {
						thesis.setAchnum("6");

					} else if (thesisForm.getT_remarks().equals("省级报纸理论、学术版")) {
						thesis.setAchnum("7");
					}
					thesis.setTusernum(tusernum);
					thesisDao.insert(thesis);
					context.setAttribute("status", "addsuccess");
					url = "thesis.do?method=query31";
					forward = new ActionForward(url);
					forward.setPath(url);
					forward.setRedirect(true);

					return forward;

				} catch (Exception e) {
					return mapping.findForward("fail1");
				}
			} else {

				FormFile file = thesisForm.getFile();// 获得文件
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();

				long FILE_SISE = 0x265480L;// 定义最大文件大小

				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdir();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();

						Date d = new Date();

						thesis.setTName(thesisForm.getT_name());
						thesis.setTPost(thesisForm.getT_post());
						thesis.setTUnit(thesisForm.getT_unit());
						thesis.setTTitle(thesisForm.getT_title());
						thesis.setTPeriodical(thesisForm.getT_periodical());
						thesis.setTCnid(thesisForm.getT_CNId());
						thesis.setTIssnid(thesisForm.getT_ISSNId());
						thesis.setTTime(d);
						thesis.setTOthers(thesisForm.getT_others());
						thesis.setTScore("未审核");
						thesis.setTRemarks(thesisForm.getT_remarks());

						thesisDao.insert(thesis);
						context.setAttribute("status", "addsuccess");
						url = "thesis.do?method=query31";
						forward = new ActionForward(url);
						forward.setPath(url);
						forward.setRedirect(true);

						return forward;

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();
						// return mapping.findForward("fail1");
					}

			}

		}

		if (method.equals("update")) {
			Keyanuser keyanuser = (Keyanuser) request.getSession()
					.getAttribute("keyanuser");
			thesisDao.update(thesisForm, keyanuser.getUsername());

			context.setAttribute("status", "updatesuccess");
			String url = "thesis.do?method=query31";
			forward = new ActionForward(url);
			forward.setPath(url);
			forward.setRedirect(true);
			return forward;
		}

		return null;
	}
}