/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.keyan.hibernate.dao.ProjectcgDao;
import com.keyan.hibernate.dao.ThesisDao;
import com.keyan.hibernate.dao.WorkDao;
import com.keyan.hibernate.dao.ZhuanliDao;
import com.keyan.struts.form.DeptCount;
import com.keyan.struts.form.TongjiForm;

/**
 * MyEclipse Struts Creation date: 03-22-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="method" validate="true"
 * @struts.action-forward name="xiangmufenxishow" path="/xiangmufenxishow.jsp"
 * @struts.action-forward name="tongjiyuanxishow" path="/tongjiyuanxishow.jsp"
 * @struts.action-forward name="yuanxifenxishow" path="/yuanxifenxishow.jsp"
 * @struts.action-forward name="tongjinianshow" path="/tongjinianshow.jsp"
 * @struts.action-forward name="tongjigerenshow" path="/tongjigerenshow.jsp"
 */
public class TongjiAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws ParseException
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws ParseException {
		// TODO Auto-generated method stub
		TongjiForm tongjiForm = (TongjiForm) form;

		String method = request.getParameter("method");
		String yuanxi[] = { "", "软件学院", "计科系", "文学院", "数科系", "艺术设计", "国教" };
		String lunwen[] = { "全部", "论著", "论文", "项目", "专利" };
		String post[] = { "教授", "副教授", "讲师", "助教" };
		String dj[] = { "国家级", "省级", "SCI" };
		ServletContext context = this.servlet.getServletContext();
		WorkDao workDao = new WorkDao();
		ZhuanliDao ZhuanliDao = new ZhuanliDao();
		ThesisDao ThesisDao = new ThesisDao();
		ProjectcgDao projectcgDao = new ProjectcgDao();
		DeptCount deptCount = new DeptCount();
		List wList = new ArrayList();
		List zList = new ArrayList();
		List tList = new ArrayList();
		List pList = new ArrayList();

		if (method.equals("tongjiyuanxishow")) {
			String nian = request.getParameter("nian");
			String yuanxi1 = request.getParameter("yuanxi");

			String leibie = request.getParameter("leibie");
			int index1 = Integer.parseInt(yuanxi1);
			int index2 = Integer.parseInt(leibie);

			String nian1 = "";
			String nian2 = "";
			if (!nian.equals("0")) {
				nian1 = nian + "-01-01";
				nian2 = nian + "-12-31";
			}
			if (leibie.equals("0")) {
				wList = workDao.queryByName("", yuanxi[index1], "", "", nian1,
						nian2);
				zList = ZhuanliDao.queryByName("", yuanxi[index1], "", "",
						nian1, nian2);
				tList = ThesisDao.queryByName("", yuanxi[index1], "", "",
						nian1, nian2);
				pList = projectcgDao.queryByName("", yuanxi[index1], "", "",
						nian1, nian2);
				System.out.println(tList.size());
			} else if (leibie.equals("1")) {
				wList = workDao.queryByName("", yuanxi[index1], "", "", nian1,
						nian2);
			} else if (leibie.equals("2")) {
				tList = ThesisDao.queryByName("", yuanxi[index1], "", "",
						nian1, nian2);
			} else if (leibie.equals("3")) {
				pList = projectcgDao.queryByName("", yuanxi[index1], "", "",
						nian1, nian2);
			} else if (leibie.equals("4")) {
				zList = ZhuanliDao.queryByName("", yuanxi[index1], "", "",
						nian1, nian2);
			}

			if (yuanxi1.equals("0")) {
				List deptCountList = new ArrayList();
				for (int i = 1; i < yuanxi.length; i++) {
					deptCount = new DeptCount();
					List wList1 = workDao.queryByName("", yuanxi[i], "", "",
							nian1, nian2);
					List zList1 = ZhuanliDao.queryByName("", yuanxi[i], "", "",
							nian1, nian2);
					List tList1 = ThesisDao.queryByName("", yuanxi[i], "", "",
							nian1, nian2);
					List pList1 = projectcgDao.queryByName("", yuanxi[i], "",
							"", nian1, nian2);
					deptCount.setDept(yuanxi[i]);
					deptCount.setWcount(wList1.size());
					deptCount.setZcount(zList1.size());
					deptCount.setTcount(tList1.size());
					deptCount.setPcount(pList1.size());

					deptCountList.add(deptCount);
				}
				context.setAttribute("deptCountList", deptCountList);
			}
			context.setAttribute("wList", wList);
			context.setAttribute("zList", zList);
			context.setAttribute("tList", tList);
			context.setAttribute("pList", pList);
			context.setAttribute("yuanxi", yuanxi1);
			context.setAttribute("lunwen", leibie);

			return mapping.findForward("tongjiyuanxishow");
		}

		if (method.equals("tongjigeren")) {
			String nian = tongjiForm.getNian();
			String yuanxi1 = tongjiForm.getYuanxi();
			String name = tongjiForm.getName();
			String leibie = tongjiForm.getLeibie();

			int index1 = Integer.parseInt(yuanxi1);
			int index2 = Integer.parseInt(leibie);

			String nian1 = "";
			String nian2 = "";
			if (!nian.equals("0")) {
				nian1 = nian + "-01-01";
				nian2 = nian + "-12-31";
			}
			if (leibie.equals("0")) {
				wList = workDao.queryByName(name, yuanxi[index1], "", "",
						nian1, nian2);
				zList = ZhuanliDao.queryByName(name, yuanxi[index1], "", "",
						nian1, nian2);
				tList = ThesisDao.queryByName(name, yuanxi[index1], "", "",
						nian1, nian2);
				pList = projectcgDao.queryByName(name, yuanxi[index1], "", "",
						nian1, nian2);

			} else if (leibie.equals("1")) {
				wList = workDao.queryByName(name, yuanxi[index1], "", "",
						nian1, nian2);
			} else if (leibie.equals("2")) {
				tList = ThesisDao.queryByName(name, yuanxi[index1], "", "",
						nian1, nian2);
			} else if (leibie.equals("3")) {
				pList = projectcgDao.queryByName(name, yuanxi[index1], "", "",
						nian1, nian2);
			} else if (leibie.equals("4")) {
				zList = ZhuanliDao.queryByName("", yuanxi[index1], "", "",
						nian1, nian2);
			}

			context.setAttribute("wList", wList);
			context.setAttribute("zList", zList);
			context.setAttribute("tList", tList);
			context.setAttribute("pList", pList);
			context.setAttribute("yuanxi", yuanxi1);
			context.setAttribute("lunwen", leibie);

			return mapping.findForward("tongjigerenshow");
		}

		if (method.equals("tongjinianshow")) {
			String nian = request.getParameter("nian");
			String nian1 = request.getParameter("nian1");
			String yuanxi1 = request.getParameter("yuanxi");

			int index1 = Integer.parseInt(yuanxi1);
			int stimeint = Integer.parseInt(nian);
			int etimeint = Integer.parseInt(nian1);

			List deptCountList = new ArrayList();

			for (int i = stimeint; i <= etimeint; i++) {
				String snian = i + "-01-01";
				String enian = i + "-12-31";

				deptCount = new DeptCount();
				wList = workDao.queryByName("", yuanxi[index1], "", "", snian,
						enian);
				zList = ZhuanliDao.queryByName("", yuanxi[index1], "", "",
						snian, enian);
				tList = ThesisDao.queryByName("", yuanxi[index1], "", "",
						snian, enian);
				pList = projectcgDao.queryByName("", yuanxi[index1], "", "",
						snian, enian);

				deptCount.setDept("" + i);
				System.out.print(yuanxi[index1] + "d");
				System.out.print(zList.size() + "d");
				System.out.print(tList.size() + "d");
				System.out.print(pList.size() + "d");
				deptCount.setWcount(wList.size() + zList.size() + tList.size()
						+ pList.size());

				deptCountList.add(deptCount);

			}
			context.setAttribute("deptCountList", deptCountList);
			context.setAttribute("yuanxi", yuanxi1);

			return mapping.findForward("tongjinianshow");
		}
		if (method.equals("xiangmufenxishow")) {
			String nian = request.getParameter("nian");
			String yuanxi1 = request.getParameter("yuanxi");

			String leibie = request.getParameter("leibie");
			int index1 = Integer.parseInt(yuanxi1);

			System.out.println(dj[index1]);
			String nian1 = "";
			String nian2 = "";
			if (!nian.equals("0")) {
				nian1 = nian + "-01-01";
				nian2 = nian + "-12-31";
			}

			wList = workDao.queryByNamef("", "", "", dj[index1], nian1, nian2);
			zList = ZhuanliDao.queryByNamef("", "", "", dj[index1], nian1,
					nian2);
			tList = ThesisDao
					.queryByNamef("", "", "", dj[index1], nian1, nian2);
			pList = projectcgDao.queryByNamef("", "", "", dj[index1], nian1,
					nian2);

			List deptCountList = new ArrayList();
			for (int i = 0; i < post.length; i++) {

				deptCount = new DeptCount();
				List wList1 = workDao.queryByNamef("", "", post[i], dj[index1],
						nian1, nian2);
				List zList1 = ZhuanliDao.queryByNamef("", "", post[i],
						dj[index1], nian1, nian2);
				List tList1 = ThesisDao.queryByNamef("", "", post[i],
						dj[index1], nian1, nian2);
				List pList1 = projectcgDao.queryByNamef("", "", post[i],
						dj[index1], nian1, nian2);
				deptCount.setDept(post[i] + "的" + dj[index1]);

				System.out.println(wList1.size() + "sss");
				System.out.println(zList1.size() + "sss");
				System.out.println(tList1.size() + "sss");
				System.out.println(pList1.size() + "sss");

				deptCount.setWcount(wList1.size());
				deptCount.setZcount(zList1.size());
				deptCount.setTcount(tList1.size());
				deptCount.setPcount(pList1.size());

				deptCountList.add(deptCount);

			}
			context.setAttribute("deptCountList", deptCountList);

			context.setAttribute("wList", wList);
			context.setAttribute("zList", zList);
			context.setAttribute("tList", tList);
			context.setAttribute("pList", pList);
			context.setAttribute("yuanxi", yuanxi1);
			context.setAttribute("lunwen", leibie);

			return mapping.findForward("xiangmufenxishow");
		}

		if (method.equals("yuanxifenxishow")) {
			String nian = request.getParameter("nian");
			String yuanxi1 = request.getParameter("yuanxi");

			String leibie = request.getParameter("leibie");
			int index1 = Integer.parseInt(yuanxi1);

			System.out.println(yuanxi[index1] + "sadsadsadsadsa");
			String nian1 = "";
			String nian2 = "";
			if (!nian.equals("0")) {
				nian1 = nian + "-01-01";
				nian2 = nian + "-12-31";
			}

			wList = workDao.queryByName("", yuanxi[index1], "", "", nian1,
					nian2);
			zList = ZhuanliDao.queryByName("", yuanxi[index1], "", "", nian1,
					nian2);
			tList = ThesisDao.queryByName("", yuanxi[index1], "", "", nian1,
					nian2);
			pList = projectcgDao.queryByName("", yuanxi[index1], "", "", nian1,
					nian2);
			System.out.println(tList.size());

			List deptCountList = new ArrayList();
			for (int i = 0; i < post.length; i++) {
				deptCount = new DeptCount();
				List wList1 = workDao.queryByName("", yuanxi[index1], post[i],
						"", nian1, nian2);
				List zList1 = ZhuanliDao.queryByName("", yuanxi[index1],
						post[i], "", nian1, nian2);
				List tList1 = ThesisDao.queryByName("", yuanxi[index1],
						post[i], "", nian1, nian2);
				List pList1 = projectcgDao.queryByName("", yuanxi[index1],
						post[i], "", nian1, nian2);
				deptCount.setDept(post[i]);
				deptCount.setWcount(wList1.size());
				deptCount.setZcount(zList1.size());
				deptCount.setTcount(tList1.size());
				deptCount.setPcount(pList1.size());
				deptCountList.add(deptCount);

			}
			context.setAttribute("deptCountList", deptCountList);
			context.setAttribute("wList", wList);
			context.setAttribute("zList", zList);
			context.setAttribute("tList", tList);
			context.setAttribute("pList", pList);
			context.setAttribute("yuanxi", yuanxi1);
			context.setAttribute("lunwen", leibie);

			return mapping.findForward("yuanxifenxishow");
		}

		return null;
	}
}