/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.keyan.hibernate.dao.WorkDao;
import com.keyan.hibernate.form.Keyanuser;
import com.keyan.hibernate.form.Work;
import com.keyan.struts.form.WorkForm;

/**
 * MyEclipse Struts Creation date: 10-05-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/work" name="workForm" input="/work.jsp"
 *                parameter="method" scope="request" validate="true"
 */
public class WorkAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		if (request.getSession().getAttribute("keyanuser") == null) {
			return mapping.findForward("logout");
		}

		WorkForm workForm = (WorkForm) form;
		String method = (String) request.getParameter("method");
		ActionErrors errors = new ActionErrors();
		ActionForward forward = new ActionForward();
		ServletContext context = this.servlet.getServletContext();
		List list = new ArrayList();
		Work work = new Work();

		WorkDao workDao = new WorkDao();

		HttpSession sesssion = request.getSession();

		if (method.equals("query3")) {

			String wd = request.getParameter("wd");

			try {
				Keyanuser keyanuser = new Keyanuser();
				keyanuser = (Keyanuser) request.getSession().getAttribute(
						"keyanuser");

				if (wd != null) {
					if (keyanuser.getUserclasify().equals("0")) {
						// 科研人员
						list = workDao.queryBy(wd, keyanuser.getName());
					} else if (keyanuser.getUserclasify().equals("1")) {
						// 院科研秘书
						list = workDao.queryBy(wd, keyanuser.getName());
					} else {
						// 校科研秘书
						list = workDao.queryBy(wd, keyanuser.getName());
					}

				} else {

					if (keyanuser.getUserclasify().equals("0")) {
						// 科研人员
						list = workDao.query(keyanuser.getName());
					} else if (keyanuser.getUserclasify().equals("1")) {
						// 院科研秘书
						list = workDao.query(keyanuser.getName());
					} else {
						// 校科研秘书
						list = workDao.query(keyanuser.getName());
					}
				}

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query33")) {

			String wd = request.getParameter("wd");

			try {

				String username = (String) request.getSession().getAttribute(
						"username");

				list = workDao.queryByname(username, wd);

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query331")) {

			String wd = request.getParameter("wd");

			try {
				Keyanuser keyanuser = (Keyanuser) request.getSession()
						.getAttribute("keyanuser");
				String userdept = keyanuser.getUserdept();

				list = workDao.queryByunit(userdept, wd);

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query31")) {

			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			try {

				list = workDao.queryByName(keyanuser.getUsername());

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query41")) {

			try {
				String username = request.getParameter("byName");
				String unit = request.getParameter("byUnit");
				String post = request.getParameter("byPost");

				String title = request.getParameter("byTitle");
				list = workDao.queryByName(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query441")) {

			try {
				String username = request.getParameter("byName");
				String unit = request.getParameter("byUnit");
				String post = request.getParameter("byPost");

				String title = request.getParameter("byTitle");
				list = workDao.queryByName1(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query442")) {

			try {

				Keyanuser keyanuser = (Keyanuser) request.getSession()
						.getAttribute("keyanuser");
				String unit = keyanuser.getUserdept();
				String username = request.getParameter("byName");

				String post = request.getParameter("byPost");

				String title = request.getParameter("byTitle");
				list = workDao.queryByName2(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query443")) {

			try {
				String username = (String) request.getSession().getAttribute(
						"username");

				String unit = request.getParameter("byUnit");
				String post = request.getParameter("byPost");

				String title = request.getParameter("byTitle");
				list = workDao.queryByName3(username, unit, post, title,
						request.getParameter("btime") + "-01-01",
						Integer.parseInt(request.getParameter("etime")) - 1
								+ "-12-31");

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		}

		// 更新
		else if (method.equals("update1")) {
			String id = request.getParameter("id");
			work = workDao.queryId(new Integer(id));
			Keyanuser keyanuser = new Keyanuser();
			keyanuser = (Keyanuser) request.getSession().getAttribute(
					"keyanuser");
			if (keyanuser.getUserclasify().equals("0")) {
			} else if (keyanuser.getUserclasify().equals("1")) {
				if (work.getWScore().equals("未审核"))
					work.setWScore("院审通过");
			} else {
				work.setWScore("校审通过");
			}

			workDao.update1(work);

			String url = "work.do?method=query32";
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;

		}

		else if (method.equals("update2")) {
			String id = request.getParameter("id");
			work = workDao.queryId(new Integer(id));
			Keyanuser keyanuser = new Keyanuser();
			keyanuser = (Keyanuser) request.getSession().getAttribute(
					"keyanuser");
			if (keyanuser.getUserclasify().equals("0")) {
			} else if (keyanuser.getUserclasify().equals("1")) {
				if (work.getWScore().equals("未审核"))
					work.setWScore("院审通过");
			} else {
				work.setWScore("校审通过");
			}

			workDao.update1(work);

			String url = "work.do?method=query3";
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;

		}

		else if (method.equals("query32")) {

			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			try {

				list = workDao.queryByUserdept(keyanuser.getUserdept());

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele1")) {
			try {

				String id = request.getParameter("id");

				workDao.delete(new Integer(id));

				String url = "work.do?method=query31";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele2")) {
			try {

				String id = request.getParameter("id");

				workDao.delete(new Integer(id));

				String url = "work.do?method=query32";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele3")) {
			try {

				String id = request.getParameter("id");

				workDao.delete(new Integer(id));

				String url = "work.do?method=query3";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("query1")) {
			try {

				String id = request.getParameter("id");

				work = workDao.queryId(new Integer(id));

				context.setAttribute("work", work);

				return mapping.findForward("query2");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("queryinfo")) {
			try {

				String id = request.getParameter("id");

				work = workDao.queryId(new Integer(id));

				context.setAttribute("work", work);

				return mapping.findForward("queryinfo");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("insert")) {
			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			String filePath = null;
			String path = null;
			String url = null;
			if (workForm.getFile().getFileName().equals("")) {
				try {

					Date d = new Date();

					work.setWName(workForm.getWName());
					work.setWPost(workForm.getWPost());
					work.setWUnit(workForm.getWUnit());
					work.setWTitle(workForm.getWTitle());
					work.setWPublisher(workForm.getWPublisher());
					work.setWIsbnid(workForm.getWIsbnid());
					work.setWTime(d);

					String wusernum = keyanuser.getUsername();

					work.setWnum(wusernum);
					work.setWScore("未审核");
					work.setWRemarks(workForm.getWRemarks());

					int num;
					if (!"".equals(workForm.getWSecond().replace(" ", ""))) {
						work.setSecond(workForm.getWSecond());
						num = 2;
						wusernum = wusernum + "," + workForm.getWSecondnum();

						if (!"".equals(workForm.getWThird().replace(" ", ""))) {
							work.setThird(workForm.getWThird());
							num = 3;
							wusernum = wusernum + "," + workForm.getWThirdnum();
							if (!"".equals(workForm.getWOthers().replace(" ",
									""))) {
								work.setWOthers(workForm.getWOthers());
								num = 3 + workForm.getWOthers().split("、").length;
								wusernum = wusernum + ","
										+ workForm.getWOthersnum();

							} else {
								work.setWOthers("无");
							}

						} else {
							work.setThird("无");
							work.setWOthers("无");
						}
						work.setWMembers(num);
					} else {
						work.setWMembers(1);
						work.setThird("无");
						work.setWOthers("无");
						work.setSecond("无");
					}
					if (workForm.getWRemarks().equals("学术专利")) {
						work.setAchnum("8");

					} else if (workForm.getWRemarks().equals("教育部推荐教材")) {
						work.setAchnum("9");

					} else if (workForm.getWRemarks().equals("其他著作或教材")) {
						work.setAchnum("10");

					} else if (workForm.getWRemarks().equals("工具书")) {
						work.setAchnum("11");

					}
					work.setWusernum(wusernum);
					workDao.insert(work);
					context.setAttribute("status", "addsuccess");
					url = "work.do?method=query31";
					forward = new ActionForward(url);
					forward.setPath(url);
					forward.setRedirect(true);

					return forward;

				} catch (Exception e) {
					return mapping.findForward("fail1");
				}
			} else {

				FormFile file = workForm.getFile();// 获得文件
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();
				long FILE_SISE = 0x265480L;// 定义最大文件大小
				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdir();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();

						Date d = new Date();

						work.setWName(workForm.getWName());
						work.setWPost(workForm.getWPost());
						work.setWUnit(workForm.getWUnit());
						work.setWTitle(workForm.getWTitle());
						work.setWPublisher(workForm.getWPublisher());
						work.setWIsbnid(workForm.getWIsbnid());
						work.setWTime(d);
						work.setWOthers(workForm.getWOthers());
						work.setWScore("未审核");
						work.setWRemarks(workForm.getWRemarks());

						workDao.insert(work);
						context.setAttribute("status", "addsuccess");
						url = "work.do?method=query31";
						forward = new ActionForward(url);
						forward.setPath(url);
						forward.setRedirect(true);

						return forward;

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();
					}

			}

		}
		if (method.equals("update")) {
			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			workDao.update(workForm, keyanuser.getUsername());

			context.setAttribute("status", "updatesuccess");
			String url = "work.do?method=query31";
			forward = new ActionForward(url);
			forward.setPath(url);
			forward.setRedirect(true);
			return forward;
		}

		return forward;
	}
}