/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.keyan.hibernate.dao.Shenpi21Dao;
import com.keyan.struts.form.XmglForm;

/**
 * MyEclipse Struts Creation date: 09-25-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/xmgl" name="xmglForm" parameter="method"
 *                scope="request" validate="true"
 */
public class XmglAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		XmglForm xmglForm = (XmglForm) form;// TODO Auto-generated method stub
		String method = request.getParameter("method");
		ActionErrors errors = new ActionErrors();
		ActionForward forward = new ActionForward();
		ServletContext context = this.servlet.getServletContext();
		Shenpi21Dao managerdao = new Shenpi21Dao();

		List colleageList = new ArrayList();
		if (method.equals("query")) {
			colleageList = managerdao.query();

			context.setAttribute("colleageList", colleageList);

			return mapping.findForward("xiangmu");
		} else if (method.equals("delete")) {
			String id = request.getParameter("id");
			managerdao.deleteById(new Integer(id));

			String url = "xmgl.do?method=query";
			forward = new ActionForward(url);
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;
		} else if (method.equals("shenpi")) {
			String id = request.getParameter("id");
			managerdao.shenpi(id);

			String url = "xmgl.do?method=query";
			forward = new ActionForward(url);
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;
		}
		return null;
	}
}