/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.action;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.keyan.hibernate.dao.ZhuanliDao;
import com.keyan.hibernate.form.Keyanuser;
import com.keyan.hibernate.form.Zhuanli;
import com.keyan.struts.form.ZhuanliForm;

/**
 * MyEclipse Struts Creation date: 3-05-2017
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/Zhuanli" name="ZhuanliForm" input="/Zhuanli.jsp"
 *                parameter="method" scope="request" validate="true"
 */
public class ZhuanliAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		if (request.getSession().getAttribute("keyanuser") == null) {
			return mapping.findForward("logout");
		}

		ZhuanliForm zhuanliForm = (ZhuanliForm) form;
		String method = (String) request.getParameter("method");
		ActionErrors errors = new ActionErrors();
		ActionForward forward = new ActionForward();
		ServletContext context = this.servlet.getServletContext();
		List list = new ArrayList();
		Zhuanli zhuanli = new Zhuanli();

		ZhuanliDao zhuanliDao = new ZhuanliDao();

		HttpSession sesssion = request.getSession();

		if (method.equals("query5")) {

			String wd = request.getParameter("wd");

			try {
				Keyanuser keyanuser = new Keyanuser();
				keyanuser = (Keyanuser) request.getSession().getAttribute(
						"keyanuser");

				if (wd != null) {
					if (keyanuser.getUserclasify().equals("0")) {
						// 科研人员
						list = zhuanliDao.queryBy(wd, keyanuser.getName());
					} else if (keyanuser.getUserclasify().equals("1")) {
						// 院科研秘书
						list = zhuanliDao.queryBy(wd, keyanuser.getName());
					} else {
						// 校科研秘书
						list = zhuanliDao.queryBy(wd, keyanuser.getName());
					}

				} else {

					if (keyanuser.getUserclasify().equals("0")) {
						// 科研人员
						list = zhuanliDao.query(keyanuser.getName());
					} else if (keyanuser.getUserclasify().equals("1")) {
						// 院科研秘书
						list = zhuanliDao.query(keyanuser.getName());
					} else {
						// 校科研秘书
						list = zhuanliDao.query(keyanuser.getName());
					}
				}

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query33")) {

			String wd = request.getParameter("wd");

			try {

				String username = (String) request.getSession().getAttribute(
						"username");

				list = zhuanliDao.queryByname(username, wd);

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query331")) {

			String wd = request.getParameter("wd");

			try {
				Keyanuser keyanuser = (Keyanuser) request.getSession()
						.getAttribute("keyanuser");
				String userdept = keyanuser.getUserdept();

				list = zhuanliDao.queryByunit(userdept, wd);

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("query31")) {

			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			try {

				list = zhuanliDao.queryByName(keyanuser.getUsername());

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		}
		// 更新
		else if (method.equals("update1")) {
			String id = request.getParameter("id");
			zhuanli = zhuanliDao.queryId(new Integer(id));
			Keyanuser keyanuser = new Keyanuser();
			keyanuser = (Keyanuser) request.getSession().getAttribute(
					"keyanuser");
			if (keyanuser.getUserclasify().equals("0")) {
			} else if (keyanuser.getUserclasify().equals("1")) {
				if (zhuanli.getZScore().equals("未审核"))
					zhuanli.setZScore("院审通过");
			} else {
				zhuanli.setZScore("校审通过");
			}

			zhuanliDao.update1(zhuanli);

			String url = "zhuanli.do?method=query32";
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;

		}

		else if (method.equals("update2")) {
			String id = request.getParameter("id");
			zhuanli = zhuanliDao.queryId(new Integer(id));
			Keyanuser keyanuser = new Keyanuser();
			keyanuser = (Keyanuser) request.getSession().getAttribute(
					"keyanuser");
			if (keyanuser.getUserclasify().equals("0")) {
			} else if (keyanuser.getUserclasify().equals("1")) {
				if (zhuanli.getZScore().equals("未审核"))
					zhuanli.setZScore("院审通过");
			} else {
				zhuanli.setZScore("校审通过");
			}

			zhuanliDao.update1(zhuanli);

			String url = "zhuanli.do?method=query5";
			forward.setPath(url);
			forward.setRedirect(true);

			return forward;

		}

		else if (method.equals("query32")) {

			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			try {

				list = zhuanliDao.queryByUserdept(keyanuser.getUserdept());

				context.setAttribute("list", list);

				return mapping.findForward("query1");

			} catch (Exception e) {
				e.printStackTrace();
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele1")) {
			try {

				String id = request.getParameter("id");

				zhuanliDao.delete(new Integer(id));

				String url = "zhuanli.do?method=query31";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele2")) {
			try {

				String id = request.getParameter("id");

				zhuanliDao.delete(new Integer(id));

				String url = "zhuanli.do?method=query32";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("detele3")) {
			try {

				String id = request.getParameter("id");

				zhuanliDao.delete(new Integer(id));

				String url = "zhuanli.do?method=query5";
				forward = new ActionForward(url);
				forward.setPath(url);
				forward.setRedirect(true);
				return forward;

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("query1")) {
			try {

				String id = request.getParameter("id");

				zhuanli = zhuanliDao.queryId(new Integer(id));

				context.setAttribute("zhuanli", zhuanli);

				return mapping.findForward("query2");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		} else if (method.equals("queryinfo")) {
			try {

				String id = request.getParameter("id");

				zhuanli = zhuanliDao.queryId(new Integer(id));

				context.setAttribute("zhuanli", zhuanli);

				return mapping.findForward("queryinfo");

			} catch (Exception e) {
				return mapping.findForward("fail1");
			}
		}

		else if (method.equals("insert")) {
			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			String filePath = null;
			String path = null;
			String url = null;
			String zusernum = keyanuser.getUsername();
			if (zhuanliForm.getFile().getFileName().equals("")) {
				try {

					Date d = new Date();

					zhuanli.setZName(zhuanliForm.getZName());
					zhuanli.setZPost(zhuanliForm.getZPost());
					zhuanli.setZDept(zhuanliForm.getZDept());
					zhuanli.setZTitle(zhuanliForm.getZTitle());
					zhuanli.setZType(zhuanliForm.getZType());
					zhuanli.setZId(zhuanliForm.getZId());
					zhuanli.setZState(zhuanliForm.getZState());
					zhuanli.setZNum(zhuanliForm.getZNum());
					zhuanli.setZTime(d);
					zhuanli.setZAward(zhuanliForm.getZAward());
					zhuanli.setZScore("未审核");
					zhuanli.setZRemarks(zhuanliForm.getZRemarks());
					zhuanli.setZnamenum(zusernum);
					int num;
					if (!"".equals(zhuanliForm.getZSecond().replace(" ", ""))) {
						num = 2;
						zusernum = zusernum + "," + zhuanliForm.getZSecondnum();
						zhuanli.setSecond(zhuanliForm.getZSecond());
						if (!"".equals(zhuanliForm.getZThird().replace(" ", ""))) {
							num = 3;
							zusernum = zusernum + ","
									+ zhuanliForm.getZThirdnum();
							zhuanli.setThird(zhuanliForm.getZThird());
							if (!"".equals(zhuanliForm.getZOthers().replace(
									" ", ""))) {
								zhuanli.setZOthers(zhuanliForm.getZOthers());
								num = 3 + zhuanli.getZOthers().split("、").length;
								zusernum = zusernum + ","
										+ zhuanliForm.getZOthersnum();

							} else {
								zhuanli.setZOthers("无");
							}
						} else {

							zhuanli.setThird("无");
							zhuanli.setZOthers("无");
						}
						zhuanli.setZMembers(num);
					} else {
						zhuanli.setSecond("无");
						zhuanli.setThird("无");
						zhuanli.setZOthers("无");
						zhuanli.setZMembers(1);
						;
					}
					if (zhuanliForm.getZRemarks().equals("发明专利")) {
						zhuanli.setAchnum("12");

					} else if (zhuanliForm.getZRemarks().equals("实用新型专利")) {
						zhuanli.setAchnum("13");

					} else if (zhuanliForm.getZRemarks().equals("外观设计专利")) {
						zhuanli.setAchnum("14");

					}

					zhuanli.setZusernum(zusernum);

					zhuanliDao.insert(zhuanli);
					context.setAttribute("status", "addsuccess");
					url = "zhuanli.do?method=query31";
					forward = new ActionForward(url);
					forward.setPath(url);
					forward.setRedirect(true);

					return forward;

				} catch (Exception e) {
					return mapping.findForward("fail1");
				}
			} else {

				FormFile file = zhuanliForm.getFile();// 获得文件
				String contentType = file.getContentType();// 获得文件类型
				String fileName = file.getFileName();// 获得文件名
				String file_type = fileName != null && !fileName.equals("") ? fileName
						.substring(fileName.lastIndexOf(".")) : "";// 获得文件后缀名
				file_type = file_type.toLowerCase();

				long FILE_SISE = 0x265480L;// 定义最大文件大小

				String size = file.getFileSize() + " bytes";
				if ((long) file.getFileSize() < FILE_SISE)// 判断文件大小
					try {
						InputStream stream = file.getInputStream();
						String newname = file.getFileName();
						filePath = this.getServlet().getServletContext()
								.getRealPath("/")
								+ "uploadImage/";// 定义上传路径
						File newfile = new File(filePath);
						if (!newfile.exists())
							newfile.mkdir();
						path = "uploadImage\\" + file_type;
						OutputStream bos = new FileOutputStream(filePath + "/"
								+ fileName);
						int bytesRead = 0;
						byte buffer[] = new byte[8192];
						while ((bytesRead = stream.read(buffer, 0, 8192)) != -1)
							bos.write(buffer, 0, bytesRead);

						bos.close();
						stream.close();

						Date d = new Date();

						zhuanli.setZName(zhuanliForm.getZName());
						zhuanli.setZPost(zhuanliForm.getZPost());
						zhuanli.setZDept(zhuanliForm.getZDept());
						zhuanli.setZTitle(zhuanliForm.getZTitle());
						zhuanli.setZType(zhuanliForm.getZType());
						zhuanli.setZId(zhuanliForm.getZId());
						zhuanli.setZState(zhuanliForm.getZState());
						zhuanli.setZNum(zhuanliForm.getZNum());
						zhuanli.setZTime(d);
						zhuanli.setZAward(zhuanliForm.getZAward());
						zhuanli.setZOthers(zhuanliForm.getZOthers());
						zhuanli.setZScore("未审核");
						zhuanli.setZRemarks(zhuanliForm.getZRemarks());

						zhuanliDao.insert(zhuanli);
						context.setAttribute("status", "addsuccess");
						url = "zhuanli.do?method=query31";
						forward = new ActionForward(url);
						forward.setPath(url);
						forward.setRedirect(true);

						return forward;

					} catch (Exception e) {

						context.setAttribute("error", "文件上传出错");

						e.printStackTrace();
					}

			}

		}

		if (method.equals("update")) {
			Keyanuser keyanuser = (Keyanuser) sesssion
					.getAttribute("keyanuser");
			zhuanliDao.update(zhuanliForm, keyanuser.getUsername());
			context.setAttribute("status", "updatesuccess");
			String url = "zhuanli.do?method=query31";
			forward = new ActionForward(url);
			forward.setPath(url);
			forward.setRedirect(true);
			return forward;
		}

		return null;
	}
}