/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/**
 * MyEclipse Struts Creation date: 07-23-2010
 * 
 * XDoclet definition:
 * 
 * @struts.form name="bgLoginForm"
 */
public class BgLoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** level property */
	private String clasify;

	/** name property */
	private String username;

	/** password property */
	private String password;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();

		if (username == null || username.equals("")) {
			errors.add("username", new ActionMessage("bgLogin.error.name"));
		}
		if (password == null || password.equals("")) {
			errors.add("password", new ActionMessage("bgLogin.error.password"));
		}

		request.setAttribute("bgLoginFormBean", this);
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the password.
	 * 
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	public String getClasify() {
		return clasify;
	}

	public void setClasify(String clasify) {
		this.clasify = clasify;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}