/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-02-2010
 * 
 * XDoclet definition:
 * @struts.form name="geSearchForm"
 */
public class GeSearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** zgnum property */
	private String zgnum;

	/** name property */
	private String name;

	/** nian1 property */
	private String nian1;

	/** nian2 property */
	private String nian2;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the zgnum.
	 * @return String
	 */
	public String getZgnum() {
		return zgnum;
	}

	/** 
	 * Set the zgnum.
	 * @param zgnum The zgnum to set
	 */
	public void setZgnum(String zgnum) {
		this.zgnum = zgnum;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the nian1.
	 * @return String
	 */
	public String getNian1() {
		return nian1;
	}

	/** 
	 * Set the nian1.
	 * @param nian1 The nian1 to set
	 */
	public void setNian1(String nian1) {
		this.nian1 = nian1;
	}

	/** 
	 * Returns the nian2.
	 * @return String
	 */
	public String getNian2() {
		return nian2;
	}

	/** 
	 * Set the nian2.
	 * @param nian2 The nian2 to set
	 */
	public void setNian2(String nian2) {
		this.nian2 = nian2;
	}
}