/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-06-2010
 * 
 * XDoclet definition:
 * @struts.form name="infoForm"
 */
public class InfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** infoform property */
	private String infoform;

	/** fujian property */
	private String fujian;

	/** context property */
	private String context;

	/** infoto property */
	private String infoto;
	private FormFile file;
	/*
	 * Generated Methods
	 */

	public FormFile getFile() {
		return file;
	}

	public void setFile(FormFile file) {
		this.file = file;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the infoform.
	 * @return String
	 */
	public String getInfoform() {
		return infoform;
	}

	/** 
	 * Set the infoform.
	 * @param infoform The infoform to set
	 */
	public void setInfoform(String infoform) {
		this.infoform = infoform;
	}

	/** 
	 * Returns the fujian.
	 * @return String
	 */
	public String getFujian() {
		return fujian;
	}

	/** 
	 * Set the fujian.
	 * @param fujian The fujian to set
	 */
	public void setFujian(String fujian) {
		this.fujian = fujian;
	}

	/** 
	 * Returns the context.
	 * @return String
	 */
	public String getContext() {
		return context;
	}

	/** 
	 * Set the context.
	 * @param context The context to set
	 */
	public void setContext(String context) {
		this.context = context;
	}

	/** 
	 * Returns the infoto.
	 * @return String
	 */
	public String getInfoto() {
		return infoto;
	}

	/** 
	 * Set the infoto.
	 * @param infoto The infoto to set
	 */
	public void setInfoto(String infoto) {
		this.infoto = infoto;
	}
}