/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-28-2011
 * 
 * XDoclet definition:
 * @struts.form name="jigouForm"
 */
public class JigouForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** deptName property */
	private String deptName;

	/** id property */
	private String id;

	/** keshiName property */
	private String keshiName;

	/** leader property */
	private String leader;

	/** deptID property */
	private String deptID;

	/** type property */
	private String type;
	private String fujiaoshou;
	private String jiaoshoucount;
	private String jiangshi;
	private String zhujiao;
	private String keshi;
	private String jigou;
	

	/*
	 * Generated Methods
	 */

	public String getFujiaoshou() {
		return fujiaoshou;
	}

	public void setFujiaoshou(String fujiaoshou) {
		this.fujiaoshou = fujiaoshou;
	}

	public String getJiaoshoucount() {
		return jiaoshoucount;
	}

	public void setJiaoshoucount(String jiaoshoucount) {
		this.jiaoshoucount = jiaoshoucount;
	}

	public String getJiangshi() {
		return jiangshi;
	}

	public void setJiangshi(String jiangshi) {
		this.jiangshi = jiangshi;
	}

	public String getZhujiao() {
		return zhujiao;
	}

	public void setZhujiao(String zhujiao) {
		this.zhujiao = zhujiao;
	}

	public String getKeshi() {
		return keshi;
	}

	public void setKeshi(String keshi) {
		this.keshi = keshi;
	}

	public String getJigou() {
		return jigou;
	}

	public void setJigou(String jigou) {
		this.jigou = jigou;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the deptName.
	 * @return String
	 */
	public String getDeptName() {
		return deptName;
	}

	/** 
	 * Set the deptName.
	 * @param deptName The deptName to set
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the keshiName.
	 * @return String
	 */
	public String getKeshiName() {
		return keshiName;
	}

	/** 
	 * Set the keshiName.
	 * @param keshiName The keshiName to set
	 */
	public void setKeshiName(String keshiName) {
		this.keshiName = keshiName;
	}

	/** 
	 * Returns the leader.
	 * @return String
	 */
	public String getLeader() {
		return leader;
	}

	/** 
	 * Set the leader.
	 * @param leader The leader to set
	 */
	public void setLeader(String leader) {
		this.leader = leader;
	}

	/** 
	 * Returns the deptID.
	 * @return String
	 */
	public String getDeptID() {
		return deptID;
	}

	/** 
	 * Set the deptID.
	 * @param deptID The deptID to set
	 */
	public void setDeptID(String deptID) {
		this.deptID = deptID;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}
}