/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-29-2011
 * 
 * XDoclet definition:
 * @struts.form name="meetingForm"
 */
public class MeetingForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** startTime property */
	private String startTime;

	/** id property */
	private String id;

	/** meetingName property */
	private String meetingName;

	/** address property */
	private String address;

	/** type1 property */
	private String type1;

	/** meetingType property */
	private String meetingType;

	/** endTime property */
	private String endTime;

	/** courseName property */
	private String courseName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the startTime.
	 * @return String
	 */
	public String getStartTime() {
		return startTime;
	}

	/** 
	 * Set the startTime.
	 * @param startTime The startTime to set
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the meetingName.
	 * @return String
	 */
	public String getMeetingName() {
		return meetingName;
	}

	/** 
	 * Set the meetingName.
	 * @param meetingName The meetingName to set
	 */
	public void setMeetingName(String meetingName) {
		this.meetingName = meetingName;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the type1.
	 * @return String
	 */
	public String getType1() {
		return type1;
	}

	/** 
	 * Set the type1.
	 * @param type1 The type1 to set
	 */
	public void setType1(String type1) {
		this.type1 = type1;
	}

	/** 
	 * Returns the meetingType.
	 * @return String
	 */
	public String getMeetingType() {
		return meetingType;
	}

	/** 
	 * Set the meetingType.
	 * @param meetingType The meetingType to set
	 */
	public void setMeetingType(String meetingType) {
		this.meetingType = meetingType;
	}

	/** 
	 * Returns the endTime.
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/** 
	 * Set the endTime.
	 * @param endTime The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/** 
	 * Returns the courseName.
	 * @return String
	 */
	public String getCourseName() {
		return courseName;
	}

	/** 
	 * Set the courseName.
	 * @param courseName The courseName to set
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}
}