/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-10-2011
 * 
 * XDoclet definition:
 * @struts.form name="piciform"
 */
public class PiciForm extends ActionForm {
	/*
	 * Generated fields
	 */
   private Integer id;
	/** pcremark property */
	private String pcremark;

	/** pcclasify property */
	private String pcclasify;

	/** pcname property */
	private String pcname;

	/** pcfinish property */
	private String pcfinish;

	/** pccome property */
	private String pccome;

	/** pcstate property */
	private String pcstate;

	/** pcstar property */
	private String pcstar;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the pcremark.
	 * @return String
	 */
	public String getPcremark() {
		return pcremark;
	}

	/** 
	 * Set the pcremark.
	 * @param pcremark The pcremark to set
	 */
	public void setPcremark(String pcremark) {
		this.pcremark = pcremark;
	}

	/** 
	 * Returns the pcclasify.
	 * @return String
	 */
	public String getPcclasify() {
		return pcclasify;
	}

	/** 
	 * Set the pcclasify.
	 * @param pcclasify The pcclasify to set
	 */
	public void setPcclasify(String pcclasify) {
		this.pcclasify = pcclasify;
	}

	/** 
	 * Returns the pcname.
	 * @return String
	 */
	public String getPcname() {
		return pcname;
	}

	/** 
	 * Set the pcname.
	 * @param pcname The pcname to set
	 */
	public void setPcname(String pcname) {
		this.pcname = pcname;
	}

	/** 
	 * Returns the pcfinish.
	 * @return String
	 */
	public String getPcfinish() {
		return pcfinish;
	}

	/** 
	 * Set the pcfinish.
	 * @param pcfinish The pcfinish to set
	 */
	public void setPcfinish(String pcfinish) {
		this.pcfinish = pcfinish;
	}

	/** 
	 * Returns the pccome.
	 * @return String
	 */
	public String getPccome() {
		return pccome;
	}

	/** 
	 * Set the pccome.
	 * @param pccome The pccome to set
	 */
	public void setPccome(String pccome) {
		this.pccome = pccome;
	}

	/** 
	 * Returns the pcstate.
	 * @return String
	 */
	public String getPcstate() {
		return pcstate;
	}

	/** 
	 * Set the pcstate.
	 * @param pcstate The pcstate to set
	 */
	public void setPcstate(String pcstate) {
		this.pcstate = pcstate;
	}

	/** 
	 * Returns the pcstar.
	 * @return String
	 */
	public String getPcstar() {
		return pcstar;
	}

	/** 
	 * Set the pcstar.
	 * @param pcstar The pcstar to set
	 */
	public void setPcstar(String pcstar) {
		this.pcstar = pcstar;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
}