/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 02-26-2011
 * 
 * XDoclet definition:
 * @struts.form name="project1form"
 */
public class Project1Form extends ActionForm {
	/*
	 * Generated fields
	 */
	private FormFile file;
	private String pstar1;
	private String pstar2;
	/** pstate2 property */
	private String pstate2;
	private String pstate3;
	private Integer pid;
	/** pstate1 property */
	private String pstate1;

	/** pfinish property */
	private String pfinish;

	/** ppname property */
	private String ppname;

	/** ppdept property */
	private String ppdept;

	/** pclassify property */
	private String pclassify;

	/** ppeople property */
	private String ppeople;

	/** pcontrol property */
	private String pcontrol;

	/** pptype property */
	private String pptype;

	/** ppwork property */
	private String ppwork;

	/** pcome property */
	private String pcome;

	/** pnum property */
	private String pnum;

	/** pdept property */
	private String pdept;

	/** pname property */
	private String pname;

	/** pform property */
	private String pform;

	/** pstar property */
	private String pstar;

	/** padjuct property */
	private FormFile padjuct;

	/** premark property */
	private String premark;

	/** ppnum property */
	private String ppnum;
	
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the pstate2.
	 * @return String
	 */
	public String getPstate2() {
		return pstate2;
	}

	/** 
	 * Set the pstate2.
	 * @param pstate2 The pstate2 to set
	 */
	public void setPstate2(String pstate2) {
		this.pstate2 = pstate2;
	}

	/** 
	 * Returns the pstate1.
	 * @return String
	 */
	public String getPstate1() {
		return pstate1;
	}

	/** 
	 * Set the pstate1.
	 * @param pstate1 The pstate1 to set
	 */
	public void setPstate1(String pstate1) {
		this.pstate1 = pstate1;
	}
	
	
	

	/** 
	 * Returns the pfinish.
	 * @return String
	 */
	public String getPfinish() {
		return pfinish;
	}

	/** 
	 * Set the pfinish.
	 * @param pfinish The pfinish to set
	 */
	public void setPfinish(String pfinish) {
		this.pfinish = pfinish;
	}

	/** 
	 * Returns the ppname.
	 * @return String
	 */
	public String getPpname() {
		return ppname;
	}

	/** 
	 * Set the ppname.
	 * @param ppname The ppname to set
	 */
	public void setPpname(String ppname) {
		this.ppname = ppname;
	}

	/** 
	 * Returns the ppdept.
	 * @return String
	 */
	public String getPpdept() {
		return ppdept;
	}

	/** 
	 * Set the ppdept.
	 * @param ppdept The ppdept to set
	 */
	public void setPpdept(String ppdept) {
		this.ppdept = ppdept;
	}

	/** 
	 * Returns the pclassify.
	 * @return String
	 */
	public String getPclassify() {
		return pclassify;
	}

	/** 
	 * Set the pclassify.
	 * @param pclassify The pclassify to set
	 */
	public void setPclassify(String pclassify) {
		this.pclassify = pclassify;
	}

	/** 
	 * Returns the ppeople.
	 * @return String
	 */
	public String getPpeople() {
		return ppeople;
	}

	/** 
	 * Set the ppeople.
	 * @param ppeople The ppeople to set
	 */
	public void setPpeople(String ppeople) {
		this.ppeople = ppeople;
	}

	/** 
	 * Returns the pcontrol.
	 * @return String
	 */
	public String getPcontrol() {
		return pcontrol;
	}

	/** 
	 * Set the pcontrol.
	 * @param pcontrol The pcontrol to set
	 */
	public void setPcontrol(String pcontrol) {
		this.pcontrol = pcontrol;
	}

	/** 
	 * Returns the pptype.
	 * @return String
	 */
	public String getPptype() {
		return pptype;
	}

	/** 
	 * Set the pptype.
	 * @param pptype The pptype to set
	 */
	public void setPptype(String pptype) {
		this.pptype = pptype;
	}

	/** 
	 * Returns the ppwork.
	 * @return String
	 */
	public String getPpwork() {
		return ppwork;
	}

	/** 
	 * Set the ppwork.
	 * @param ppwork The ppwork to set
	 */
	public void setPpwork(String ppwork) {
		this.ppwork = ppwork;
	}

	/** 
	 * Returns the pcome.
	 * @return String
	 */
	public String getPcome() {
		return pcome;
	}

	/** 
	 * Set the pcome.
	 * @param pcome The pcome to set
	 */
	public void setPcome(String pcome) {
		this.pcome = pcome;
	}

	/** 
	 * Returns the pnum.
	 * @return String
	 */
	public String getPnum() {
		return pnum;
	}

	/** 
	 * Set the pnum.
	 * @param pnum The pnum to set
	 */
	public void setPnum(String pnum) {
		this.pnum = pnum;
	}

	/** 
	 * Returns the pdept.
	 * @return String
	 */
	public String getPdept() {
		return pdept;
	}

	/** 
	 * Set the pdept.
	 * @param pdept The pdept to set
	 */
	public void setPdept(String pdept) {
		this.pdept = pdept;
	}

	/** 
	 * Returns the pname.
	 * @return String
	 */
	public String getPname() {
		return pname;
	}

	/** 
	 * Set the pname.
	 * @param pname The pname to set
	 */
	public void setPname(String pname) {
		this.pname = pname;
	}

	/** 
	 * Returns the pform.
	 * @return String
	 */
	public String getPform() {
		return pform;
	}

	/** 
	 * Set the pform.
	 * @param pform The pform to set
	 */
	public void setPform(String pform) {
		this.pform = pform;
	}

	/** 
	 * Returns the pstar.
	 * @return String
	 */
	public String getPstar() {
		return pstar;
	}

	/** 
	 * Set the pstar.
	 * @param pstar The pstar to set
	 */
	public void setPstar(String pstar) {
		this.pstar = pstar;
	}

	/** 
	 * Returns the padjuct.
	 * @return String
	 */
	

	/** 
	 * Returns the premark.
	 * @return String
	 */
	public String getPremark() {
		return premark;
	}

	/** 
	 * Set the premark.
	 * @param premark The premark to set
	 */
	public void setPremark(String premark) {
		this.premark = premark;
	}

	/** 
	 * Returns the ppnum.
	 * @return String
	 */
	public String getPpnum() {
		return ppnum;
	}

	/** 
	 * Set the ppnum.
	 * @param ppnum The ppnum to set
	 */
	public void setPpnum(String ppnum) {
		this.ppnum = ppnum;
	}

	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPstate3() {
		return pstate3;
	}

	public void setPstate3(String pstate3) {
		this.pstate3 = pstate3;
	}

	public String getPstar1() {
		return pstar1;
	}

	public void setPstar1(String pstar1) {
		this.pstar1 = pstar1;
	}

	public String getPstar2() {
		return pstar2;
	}

	public void setPstar2(String pstar2) {
		this.pstar2 = pstar2;
	}

	public FormFile getPadjuct() {
		return padjuct;
	}

	public void setPadjuct(FormFile padjuct) {
		this.padjuct = padjuct;
	}
}