/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2010
 * 
 * XDoclet definition:
 * @struts.form name="workForm"
 */
public class ProjectcgForm extends ActionForm {
	/*
	 * Generated fields
	 */
	
	
	private FormFile file;
	private Integer id;
	private String PName;
	private String PPost;
	private String PDept;
	private String PTitle;
	private String PUnit;
	private String PId;
    private String PTime;
	private String POthers;
	private String PScore;
	private String PRemarks;
	private String PSecond;
	private String PThird;
	private String PSecondnum;
	private String PThirdnum;
	private String POthersnum;
	public String getPSecondnum() {
		return PSecondnum;
	}
	public void setPSecondnum(String pSecondnum) {
		PSecondnum = pSecondnum;
	}
	public String getPThirdnum() {
		return PThirdnum;
	}
	public void setPThirdnum(String pThirdnum) {
		PThirdnum = pThirdnum;
	}
	public String getPOthersnum() {
		return POthersnum;
	}
	public void setPOthersnum(String pOthersnum) {
		POthersnum = pOthersnum;
	}
	public String getPSecond() {
		return PSecond;
	}
	public void setPSecond(String pSecond) {
		PSecond = pSecond;
	}
	public String getPThird() {
		return PThird;
	}
	public void setPThird(String pThird) {
		PThird = pThird;
	}
	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getPName() {
		return PName;
	}
	public void setPName(String name) {
		PName = name;
	}
	public String getPPost() {
		return PPost;
	}
	public void setPPost(String post) {
		PPost = post;
	}
	public String getPDept() {
		return PDept;
	}
	public void setPDept(String dept) {
		PDept = dept;
	}
	public String getPTitle() {
		return PTitle;
	}
	public void setPTitle(String title) {
		PTitle = title;
	}
	public String getPUnit() {
		return PUnit;
	}
	public void setPUnit(String unit) {
		PUnit = unit;
	}
	public String getPId() {
		return PId;
	}
	public void setPId(String id) {
		PId = id;
	}
	public String getPTime() {
		return PTime;
	}
	public void setPTime(String time) {
		PTime = time;
	}
	public String getPOthers() {
		return POthers;
	}
	public void setPOthers(String others) {
		POthers = others;
	}
	public String getPScore() {
		return PScore;
	}
	public void setPScore(String score) {
		PScore = score;
	}
	public String getPRemarks() {
		return PRemarks;
	}
	public void setPRemarks(String remarks) {
		PRemarks = remarks;
	}
	
	
}