/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 07-23-2010
 * 
 * XDoclet definition:
 * @struts.form name="bgLoginForm"
 */
public class ShenqiForm extends ActionForm {
	/*
	 * Generated fields
	 */

	
	private String pname;
	private String pcomes;
	private String ppeople;
	private String ptype;
	private String pdept;
	private String psource;
	private String pothers;
	
	

	

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		
		if (pname == null || pname.equals("")) {
			errors.add("pname", new ActionMessage(
					"bgLogin.error.pname"));
		}
		if (pcomes == null|| pcomes.equals("")) {
			errors.add("pcomes", new ActionMessage(
					"bgLogin.error.pcomes"));
		}
		if (ptype == null|| ptype.equals("")) {
			errors.add("ptype", new ActionMessage(
					"bgLogin.error.ptype"));
		}
		if (pdept == null|| pdept.equals("")) {
			errors.add("pdept", new ActionMessage(
					"bgLogin.error.pdept"));
		}
		if (pothers == null||pothers.equals("")) {
			errors.add("pcomes", new ActionMessage(
					"bgLogin.error.pothers"));
		}
		if (ppeople == null|| ppeople.equals("")) {
			errors.add("ppeople", new ActionMessage(
					"bgLogin.error.ppeople"));
		}
		
		request.setAttribute("bgLoginFormBean", this);
		return errors;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPcomes() {
		return pcomes;
	}

	public void setPcomes(String pcomes) {
		this.pcomes = pcomes;
	}

	public String getPpeople() {
		return ppeople;
	}

	public void setPpeople(String ppeople) {
		this.ppeople = ppeople;
	}

	public String getPtype() {
		return ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	public String getPdept() {
		return pdept;
	}

	public void setPdept(String pdept) {
		this.pdept = pdept;
	}

	public String getPsource() {
		return psource;
	}

	public void setPsource(String psource) {
		this.psource = psource;
	}

	public String getPothers() {
		return pothers;
	}

	public void setPothers(String pothers) {
		this.pothers = pothers;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
}