/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-09-2010
 * 
 * XDoclet definition:
 * @struts.form name="shenpi1From"
 */
public class Shenpi1From extends ActionForm {
	/*
	 * Generated fields
	 */

	/** pcomes property */
	private String pcomes;

	/** pdept property */
	private String pdept;

	/** pname property */
	private String pname;

	/** pothers property */
	private String pothers;

	/** psource property */
	private String psource;

	/** ptype property */
	private String ptype;

	/** ppeople property */
	private String ppeople;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		
		if (pname == null || pname.equals("")) {
			errors.add("pname", new ActionMessage(
					"bgLogin.error.pname"));
		}
//		if (pcomes == null|| pcomes.equals("")) {
//			errors.add("pcomes", new ActionMessage(
//					"bgLogin.error.pcomes"));
//		}
//		if (ptype == null|| ptype.equals("")) {
//			errors.add("ptype", new ActionMessage(
//					"bgLogin.error.ptype"));
//		}
//		if (pdept == null|| pdept.equals("")) {
//			errors.add("pdept", new ActionMessage(
//					"bgLogin.error.pdept"));
//		}
		if (pothers == null||pothers.equals("")) {
			errors.add("pcomes", new ActionMessage(
					"bgLogin.error.pothers"));
		}
		if (ppeople == null|| ppeople.equals("")) {
			errors.add("ppeople", new ActionMessage(
					"bgLogin.error.ppeople"));
		}
		
		request.setAttribute("bgLoginFormBean", this);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the pcomes.
	 * @return String
	 */
	public String getPcomes() {
		return pcomes;
	}

	/** 
	 * Set the pcomes.
	 * @param pcomes The pcomes to set
	 */
	public void setPcomes(String pcomes) {
		this.pcomes = pcomes;
	}

	/** 
	 * Returns the pdept.
	 * @return String
	 */
	public String getPdept() {
		return pdept;
	}

	/** 
	 * Set the pdept.
	 * @param pdept The pdept to set
	 */
	public void setPdept(String pdept) {
		this.pdept = pdept;
	}

	/** 
	 * Returns the pname.
	 * @return String
	 */
	public String getPname() {
		return pname;
	}

	/** 
	 * Set the pname.
	 * @param pname The pname to set
	 */
	public void setPname(String pname) {
		this.pname = pname;
	}

	/** 
	 * Returns the pothers.
	 * @return String
	 */
	public String getPothers() {
		return pothers;
	}

	/** 
	 * Set the pothers.
	 * @param pothers The pothers to set
	 */
	public void setPothers(String pothers) {
		this.pothers = pothers;
	}

	/** 
	 * Returns the psource.
	 * @return String
	 */
	public String getPsource() {
		return psource;
	}

	/** 
	 * Set the psource.
	 * @param psource The psource to set
	 */
	public void setPsource(String psource) {
		this.psource = psource;
	}

	/** 
	 * Returns the ptype.
	 * @return String
	 */
	public String getPtype() {
		return ptype;
	}

	/** 
	 * Set the ptype.
	 * @param ptype The ptype to set
	 */
	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	/** 
	 * Returns the ppeople.
	 * @return String
	 */
	public String getPpeople() {
		return ppeople;
	}

	/** 
	 * Set the ppeople.
	 * @param ppeople The ppeople to set
	 */
	public void setPpeople(String ppeople) {
		this.ppeople = ppeople;
	}
}