/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2010
 * 
 * XDoclet definition:
 * @struts.form name="thesisForm"
 */
public class ThesisForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private FormFile file;
	/** t_CNId property */
	private String t_CNId;

	/** id property */
	private String id;

	/** t_score property */
	private String t_score;

	/** t_others property */
	private String t_others;

	/** post property */
	private String t_unit;

	/** t_remarks property */
	private String t_remarks;

	/** name property */
	private String t_name;

	/** t_ISSNId property */
	private String t_ISSNId;

	/** dept property */
	private String t_post;

	/** t_time property */
	private String t_time;

	/** t_periodical property */
	private String t_periodical;

	/** t_title property */
	private String t_title;
	private String second;
	private String third;
	private String t_usernum;
	private String secondnum;
	private String thirdnum;
	private String t_othersnum;
	/*
	 * Generated Methods
	 */

	public String getSecondnum() {
		return secondnum;
	}

	public void setSecondnum(String secondnum) {
		this.secondnum = secondnum;
	}

	public String getThirdnum() {
		return thirdnum;
	}

	public void setThirdnum(String thirdnum) {
		this.thirdnum = thirdnum;
	}

	public String getT_othersnum() {
		return t_othersnum;
	}

	public void setT_othersnum(String t_othersnum) {
		this.t_othersnum = t_othersnum;
	}

	public String getSecond() {
		return second;
	}

	public String getT_usernum() {
		return t_usernum;
	}

	public void setT_usernum(String t_usernum) {
		this.t_usernum = t_usernum;
	}

	public void setSecond(String second) {
		this.second = second;
	}

	public String getThird() {
		return third;
	}

	public void setThird(String third) {
		this.third = third;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the t_CNId.
	 * @return String
	 */
	public String getT_CNId() {
		return t_CNId;
	}

	/** 
	 * Set the t_CNId.
	 * @param t_CNId The t_CNId to set
	 */
	public void setT_CNId(String t_CNId) {
		this.t_CNId = t_CNId;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the t_score.
	 * @return String
	 */
	public String getT_score() {
		return t_score;
	}

	/** 
	 * Set the t_score.
	 * @param t_score The t_score to set
	 */
	public void setT_score(String t_score) {
		this.t_score = t_score;
	}

	/** 
	 * Returns the t_others.
	 * @return String
	 */
	public String getT_others() {
		return t_others;
	}

	/** 
	 * Set the t_others.
	 * @param t_others The t_others to set
	 */
	public void setT_others(String t_others) {
		this.t_others = t_others;
	}

	/** 
	 * Returns the post.
	 * @return String
	 */
	public String getT_post() {
		return t_post;
	}

	/** 
	 * Set the post.
	 * @param post The post to set
	 */
	public void setT_post(String t_post) {
		this.t_post =t_post;
	}

	/** 
	 * Returns the t_remarks.
	 * @return String
	 */
	public String getT_remarks() {
		return t_remarks;
	}

	/** 
	 * Set the t_remarks.
	 * @param t_remarks The t_remarks to set
	 */
	public void setT_remarks(String t_remarks) {
		this.t_remarks = t_remarks;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getT_name() {
		return t_name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setT_name(String t_name) {
		this.t_name = t_name;
	}

	/** 
	 * Returns the t_ISSNId.
	 * @return String
	 */
	public String getT_ISSNId() {
		return t_ISSNId;
	}

	/** 
	 * Set the t_ISSNId.
	 * @param t_ISSNId The t_ISSNId to set
	 */
	public void setT_ISSNId(String t_ISSNId) {
		this.t_ISSNId = t_ISSNId;
	}

	/** 
	 * Returns the dept.
	 * @return String
	 */
	public String getT_unit() {
		return t_unit;
	}

	/** 
	 * Set the dept.
	 * @param dept The dept to set
	 */
	public void setT_unit(String t_unit) {
		this.t_unit =t_unit ;
	}

	/** 
	 * Returns the t_time.
	 * @return String
	 */
	public String getT_time() {
		return t_time;
	}

	/** 
	 * Set the t_time.
	 * @param t_time The t_time to set
	 */
	public void setT_time(String t_time) {
		this.t_time = t_time;
	}

	/** 
	 * Returns the t_periodical.
	 * @return String
	 */
	public String getT_periodical() {
		return t_periodical;
	}

	/** 
	 * Set the t_periodical.
	 * @param t_periodical The t_periodical to set
	 */
	public void setT_periodical(String t_periodical) {
		this.t_periodical = t_periodical;
	}

	/** 
	 * Returns the t_title.
	 * @return String
	 */
	public String getT_title() {
		return t_title;
	}

	/** 
	 * Set the t_title.
	 * @param t_title The t_title to set
	 */
	public void setT_title(String t_title) {
		this.t_title = t_title;
	}

	public FormFile getFile() {
		return file;
	}

	public void setFile(FormFile file) {
		this.file = file;
	}
}