/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2010
 * 
 * XDoclet definition:
 * @struts.form name="workForm"
 */
public class WorkForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private FormFile file;
	private Integer id;
	private String WName;
	private String WPost;
	private String WUnit;
	private String WTitle;
	private String WPublisher;
	private String WIsbnid;
    private String WTime;
	private String WOthers;
	private String WScore;
	private String WRemarks;
	private String WSecond;
	private String WThird;
	private String Wusernum;
	private String WOthersnum;
	private String WSecondnum;
	private String WThirdnum;
	public String getWusernum() {
		return Wusernum;
	}
	public void setWusernum(String wusernum) {
		Wusernum = wusernum;
	}
	public String getWOthersnum() {
		return WOthersnum;
	}
	public void setWOthersnum(String wOthersnum) {
		WOthersnum = wOthersnum;
	}
	
	public String getWSecondnum() {
		return WSecondnum;
	}
	public void setWSecondnum(String wSecondnum) {
		WSecondnum = wSecondnum;
	}
	public String getWThirdnum() {
		return WThirdnum;
	}
	public void setWThirdnum(String wThirdnum) {
		WThirdnum = wThirdnum;
	}
	public String getWSecond() {
		return WSecond;
	}
	public void setWSecond(String wSecond) {
		WSecond = wSecond;
	}
	public String getWThird() {
		return WThird;
	}
	public void setWThird(String wThird) {
		WThird = wThird;
	}
	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getWName() {
		return WName;
	}
	public void setWName(String name) {
		WName = name;
	}
	public String getWPost() {
		return WPost;
	}
	public void setWPost(String post) {
		WPost = post;
	}
	public String getWUnit() {
		return WUnit;
	}
	public void setWUnit(String unit) {
		WUnit = unit;
	}
	public String getWTitle() {
		return WTitle;
	}
	public void setWTitle(String title) {
		WTitle = title;
	}
	public String getWPublisher() {
		return WPublisher;
	}
	public void setWPublisher(String publisher) {
		WPublisher = publisher;
	}
	public String getWIsbnid() {
		return WIsbnid;
	}
	public void setWIsbnid(String isbnid) {
		WIsbnid = isbnid;
	}

	public String getWTime() {
		return WTime;
	}

	public void setWTime(String wTime) {
		WTime = wTime;
	}
	public String getWOthers() {
		return WOthers;
	}
	public void setWOthers(String others) {
		WOthers = others;
	}
	public String getWScore() {
		return WScore;
	}
	public void setWScore(String score) {
		WScore = score;
	}
	public String getWRemarks() {
		return WRemarks;
	}
	public void setWRemarks(String remarks) {
		WRemarks = remarks;
	}
}