/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.keyan.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2010
 * 
 * XDoclet definition:
 * @struts.form name=""
 */
public class ZhuanliForm extends ActionForm {
	/*
	 * Generated fields
	 */

		
	private FormFile file;
	private Integer id;
	private String ZName;
	private String ZPost;
	private String ZDept;
	private String ZTitle;
	private String ZType;
	private String ZId;
	private String ZState;
    private String ZNum;
    private String ZTime;
    private String ZAward;
    private String ZOthers;
	private String ZScore;
	private String ZRemarks;
	private String ZSecond;
	private String ZThird;
	private String ZOthersnum;
	public String getZOthersnum() {
		return ZOthersnum;
	}
	public void setZOthersnum(String zOthersnum) {
		ZOthersnum = zOthersnum;
	}
	public String getZSecondnum() {
		return ZSecondnum;
	}
	public void setZSecondnum(String zSecondnum) {
		ZSecondnum = zSecondnum;
	}
	public String getZThirdnum() {
		return ZThirdnum;
	}
	public void setZThirdnum(String zThirdnum) {
		ZThirdnum = zThirdnum;
	}
	private String ZSecondnum;
	private String ZThirdnum;
	public String getZSecond() {
		return ZSecond;
	}
	public void setZSecond(String zSecond) {
		ZSecond = zSecond;
	}
	public String getZThird() {
		return ZThird;
	}
	public void setZThird(String zThird) {
		ZThird = zThird;
	}
	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getZName() {
		return ZName;
	}
	public void setZName(String name) {
		ZName = name;
	}
	public String getZPost() {
		return ZPost;
	}
	public void setZPost(String post) {
		ZPost = post;
	}
	public String getZDept() {
		return ZDept;
	}
	public void setZDept(String dept) {
		ZDept = dept;
	}
	public String getZTitle() {
		return ZTitle;
	}
	public void setZTitle(String title) {
		ZTitle = title;
	}
	public String getZType() {
		return ZType;
	}
	public void setZType(String type) {
		ZType = type;
	}
	public String getZId() {
		return ZId;
	}
	public void setZId(String id) {
		ZId = id;
	}
	public String getZState() {
		return ZState;
	}
	public void setZState(String state) {
		ZState = state;
	}
	public String getZNum() {
		return ZNum;
	}
	public void setZNum(String num) {
		ZNum = num;
	}
	public String getZTime() {
		return ZTime;
	}
	public void setZTime(String time) {
		ZTime = time;
	}
	public String getZAward() {
		return ZAward;
	}
	public void setZAward(String award) {
		ZAward = award;
	}
	public String getZOthers() {
		return ZOthers;
	}
	public void setZOthers(String others) {
		ZOthers = others;
	}
	public String getZScore() {
		return ZScore;
	}
	public void setZScore(String score) {
		ZScore = score;
	}
	public String getZRemarks() {
		return ZRemarks;
	}
	public void setZRemarks(String remarks) {
		ZRemarks = remarks;
	}
}